-- Expanded category catalog (~175 new). INSERT IGNORE: rows whose name/slug
-- already exist are skipped, so this is safe to run on any environment.
-- sort_order blocks: 100s tech, 200s career, 300s education, 400s finance,
-- 500s health, 600s lifestyle, 700s India/local, 800s entertainment & sports,
-- 900s science/society/misc. Existing 8 broad categories keep 1-99.
INSERT IGNORE INTO categories (name, slug, description, icon, sort_order) VALUES
    -- Technology (100s)
    ('Web Development', 'web-development', 'HTML, CSS, JavaScript, frameworks, full-stack', '🌐', 101),
    ('Mobile App Development', 'mobile-app-development', 'Android, iOS, Flutter, React Native', '📱', 102),
    ('Programming Languages', 'programming-languages', 'Python, Java, C++, PHP, Go and more', '⌨️', 103),
    ('Data Science & Analytics', 'data-science-analytics', 'Statistics, ML models, data visualization', '📊', 104),
    ('Artificial Intelligence', 'artificial-intelligence', 'AI tools, LLMs, prompt engineering, ML', '🤖', 105),
    ('Cybersecurity', 'cybersecurity', 'Online safety, hacking prevention, privacy', '🔐', 106),
    ('Cloud Computing', 'cloud-computing', 'AWS, Azure, GCP, hosting, DevOps', '☁️', 107),
    ('Databases', 'databases', 'SQL, NoSQL, database design and tuning', '🗄️', 108),
    ('Networking & Internet', 'networking-internet', 'WiFi, routers, ISPs, connectivity issues', '📡', 109),
    ('Computers & Laptops', 'computers-laptops', 'Buying advice, repairs, upgrades', '🖥️', 110),
    ('Smartphones & Gadgets', 'smartphones-gadgets', 'Phone comparisons, wearables, accessories', '📲', 111),
    ('Software & Apps', 'software-apps', 'App recommendations, troubleshooting, how-tos', '💿', 112),
    ('Operating Systems', 'operating-systems', 'Windows, macOS, Linux, Android, iOS', '🐧', 113),
    ('Game Development', 'game-development', 'Unity, Unreal, game design and publishing', '🎮', 114),
    ('Blockchain & Crypto Tech', 'blockchain-crypto-tech', 'Smart contracts, web3 development', '⛓️', 115),
    ('Tech Support & Troubleshooting', 'tech-support', 'Fix errors, crashes and device problems', '🛠️', 116),
    ('Gadget Buying Advice', 'gadget-buying-advice', 'Which one should I buy? Compare before you pay', '🛒', 117),
    ('SEO & Digital Tools', 'seo-digital-tools', 'Search rankings, analytics, webmaster tools', '🔍', 118),
    ('No-Code & Automation', 'no-code-automation', 'Zapier, n8n, website builders, workflows', '⚙️', 119),
    ('UI/UX Design', 'ui-ux-design', 'Interfaces, usability, Figma, product design', '🎯', 120),
    -- Career & Jobs (200s)
    ('Career Guidance', 'career-guidance', 'Choosing and switching career paths', '🧭', 201),
    ('Resume & Interviews', 'resume-interviews', 'CV reviews, interview prep, negotiations', '📄', 202),
    ('Government Jobs', 'government-jobs', 'Sarkari naukri, vacancies, selection process', '🏛️', 203),
    ('IT & Software Jobs', 'it-software-jobs', 'Tech hiring, placements, career growth', '👨‍💻', 204),
    ('Freelancing', 'freelancing', 'Finding clients, platforms, pricing your work', '🧑‍💻', 205),
    ('Work From Home', 'work-from-home', 'Remote jobs, online earning, home office', '🏡', 206),
    ('Internships', 'internships', 'Finding internships, stipends, experience letters', '🎓', 207),
    ('Workplace Advice', 'workplace-advice', 'Office politics, appraisals, HR issues', '🏢', 208),
    ('Business Ideas & Startups', 'business-ideas-startups', 'Validation, funding, incorporation', '🚀', 209),
    ('Small Business & MSME', 'small-business-msme', 'Shops, services, Udyam registration, growth', '🏪', 210),
    ('Marketing & Sales', 'marketing-sales', 'Digital marketing, ads, lead generation', '📣', 211),
    ('E-commerce & Selling Online', 'ecommerce-selling-online', 'Amazon, Flipkart, Meesho, D2C stores', '🛍️', 212),
    ('Content Creation', 'content-creation', 'YouTube, blogging, podcasting, monetization', '🎥', 213),
    ('Skilled Trades', 'skilled-trades', 'Electricians, plumbers, mechanics, technicians', '🔧', 214),
    ('Teaching & Coaching Careers', 'teaching-coaching-careers', 'Tutoring, coaching institutes, online teaching', '👩‍🏫', 215),
    -- Education & Exams (300s)
    ('UPSC & Civil Services', 'upsc-civil-services', 'IAS, IPS, state PCS preparation', '📜', 301),
    ('SSC & Banking Exams', 'ssc-banking-exams', 'SSC CGL, IBPS, SBI PO, RBI exams', '🏦', 302),
    ('JEE & Engineering Entrance', 'jee-engineering-entrance', 'JEE Main, Advanced, state CETs', '📐', 303),
    ('NEET & Medical Entrance', 'neet-medical-entrance', 'NEET UG/PG, AIIMS, medical admissions', '⚕️', 304),
    ('CAT & MBA Entrance', 'cat-mba-entrance', 'CAT, XAT, GMAT, B-school admissions', '📈', 305),
    ('Board Exams (10th & 12th)', 'board-exams', 'CBSE, ICSE, state boards, results', '📝', 306),
    ('College Admissions', 'college-admissions', 'Choosing colleges, cutoffs, counselling', '🏫', 307),
    ('Study Abroad', 'study-abroad', 'IELTS, TOEFL, GRE, university applications', '🌍', 308),
    ('Scholarships & Financial Aid', 'scholarships-financial-aid', 'Scholarships, education loans, fee waivers', '🎖️', 309),
    ('Online Courses & Certifications', 'online-courses-certifications', 'MOOCs, Coursera, Udemy, certificates worth it?', '🖱️', 310),
    ('School Homework Help', 'school-homework-help', 'Math, science and subject doubts', '✏️', 311),
    ('English & Communication', 'english-communication', 'Spoken English, writing, public speaking', '🗣️', 312),
    ('Languages Learning', 'languages-learning', 'Hindi, regional and foreign languages', '🈯', 313),
    ('Defence Exams (NDA/CDS)', 'defence-exams', 'NDA, CDS, AFCAT, Agniveer recruitment', '🎖', 314),
    ('Railway Exams', 'railway-exams', 'RRB NTPC, Group D, loco pilot exams', '🚆', 315),
    ('State Government Exams', 'state-government-exams', 'State PSCs, police, patwari, teacher eligibility', '🗺️', 316),
    ('Law Entrance & LLB', 'law-entrance-llb', 'CLAT, judiciary exams, law school', '⚖️', 317),
    ('CA, CS & CMA', 'ca-cs-cma', 'Chartered accountancy and company secretary path', '🧮', 318),
    -- Money & Finance (400s)
    ('Personal Finance', 'personal-finance', 'Budgeting, saving, money management', '💰', 401),
    ('Stock Market & Trading', 'stock-market-trading', 'Shares, F&O, technical analysis, brokers', '📉', 402),
    ('Mutual Funds & SIP', 'mutual-funds-sip', 'Fund selection, SIPs, portfolio review', '🪙', 403),
    ('Cryptocurrency Investing', 'cryptocurrency-investing', 'Bitcoin, exchanges, taxation on crypto', '₿', 404),
    ('Income Tax & GST', 'income-tax-gst', 'ITR filing, GST returns, tax saving', '🧾', 405),
    ('Banking & UPI', 'banking-upi', 'Accounts, UPI issues, net banking, KYC', '💳', 406),
    ('Loans & Credit', 'loans-credit', 'Home, personal, education loans, CIBIL score', '🏗️', 407),
    ('Insurance', 'insurance', 'Health, term, vehicle insurance and claims', '🛡️', 408),
    ('Retirement & Pension', 'retirement-pension', 'EPF, NPS, PPF, retirement planning', '👴', 409),
    ('Real Estate & Property', 'real-estate-property', 'Buying, renting, RERA, registration', '🏘️', 410),
    ('Gold & Commodities', 'gold-commodities', 'Gold schemes, sovereign bonds, silver', '🥇', 411),
    ('Online Earning & Side Income', 'online-earning-side-income', 'Legit ways to earn online, passive income', '💵', 412),
    ('Frauds & Scam Awareness', 'frauds-scam-awareness', 'Spot and report scams, recover from fraud', '🚨', 413),
    -- Health & Wellness (500s)
    ('General Health', 'general-health', 'Symptoms, first aid, when to see a doctor', '🏥', 501),
    ('Fitness & Exercise', 'fitness-exercise', 'Gym, home workouts, yoga, running', '🏋️', 502),
    ('Diet & Nutrition', 'diet-nutrition', 'Meal plans, weight management, supplements', '🥗', 503),
    ('Mental Health', 'mental-health', 'Stress, anxiety, therapy, self-care', '🧠', 504),
    ('Women''s Health', 'womens-health', 'Periods, PCOS, pregnancy, menopause', '👩', 505),
    ('Men''s Health', 'mens-health', 'Fitness, hormones, male-specific concerns', '👨', 506),
    ('Child Health & Parenting', 'child-health-parenting', 'Baby care, vaccinations, child development', '👶', 507),
    ('Skin & Hair Care', 'skin-hair-care', 'Dermatology, hair fall, skincare routines', '💆', 508),
    ('Dental Care', 'dental-care', 'Teeth, braces, oral hygiene', '🦷', 509),
    ('Eye & Vision Care', 'eye-vision-care', 'Eyesight, glasses, LASIK, eye strain', '👁️', 510),
    ('Ayurveda & Home Remedies', 'ayurveda-home-remedies', 'Traditional medicine, natural remedies', '🌿', 511),
    ('Chronic Conditions', 'chronic-conditions', 'Diabetes, BP, thyroid, long-term care', '📋', 512),
    ('Sleep & Recovery', 'sleep-recovery', 'Insomnia, sleep hygiene, rest', '😴', 513),
    ('Addiction & Deaddiction', 'addiction-deaddiction', 'Quitting smoking, alcohol, screen addiction', '🚭', 514),
    -- Lifestyle & Home (600s)
    ('Cooking & Recipes', 'cooking-recipes', 'Indian and world cuisine, kitchen tips', '🍳', 601),
    ('Home Improvement & DIY', 'home-improvement-diy', 'Repairs, renovation, interiors', '🔨', 602),
    ('Gardening & Plants', 'gardening-plants', 'Home gardens, terrace farming, plant care', '🪴', 603),
    ('Relationships & Dating', 'relationships-dating', 'Love, breakups, communication', '❤️', 604),
    ('Marriage & Family', 'marriage-family', 'Married life, in-laws, family dynamics', '👪', 605),
    ('Parenting & Kids', 'parenting-kids', 'Raising children, schooling decisions, teens', '🧒', 606),
    ('Weddings & Events', 'weddings-events', 'Wedding planning, budgets, ceremonies', '💒', 607),
    ('Fashion & Style', 'fashion-style', 'Outfits, trends, grooming', '👗', 608),
    ('Beauty & Makeup', 'beauty-makeup', 'Makeup techniques, products, tutorials', '💄', 609),
    ('Pets & Animal Care', 'pets-animal-care', 'Dogs, cats, pet food, vet advice', '🐕', 610),
    ('Shopping & Deals', 'shopping-deals', 'Best buys, sales, product experiences', '🏷️', 611),
    ('Personal Development', 'personal-development', 'Habits, productivity, confidence, discipline', '🌱', 612),
    ('Spirituality & Meditation', 'spirituality-meditation', 'Meditation, mindfulness, spiritual practice', '🕉️', 613),
    ('Etiquette & Social Skills', 'etiquette-social-skills', 'Social situations, manners, networking', '🤝', 614),
    ('Hobbies & Crafts', 'hobbies-crafts', 'Art, collecting, model making, crafts', '🧶', 615),
    ('Books & Reading', 'books-reading', 'Recommendations, reviews, reading habits', '📖', 616),
    ('Photography', 'photography', 'Cameras, composition, editing, phone photography', '📷', 617),
    ('Writing & Blogging', 'writing-blogging', 'Creative writing, blogging, publishing', '✍️', 618),
    ('Music & Instruments', 'music-instruments', 'Learning instruments, singing, production', '🎸', 619),
    ('Dance & Performing Arts', 'dance-performing-arts', 'Dance forms, theatre, performance', '💃', 620),
    -- India & Local (700s)
    ('Aadhaar, PAN & Documents', 'aadhaar-pan-documents', 'ID cards, corrections, linking, DigiLocker', '🪪', 701),
    ('Passport & Visa', 'passport-visa', 'Passport application, visas, immigration', '🛂', 702),
    ('Government Schemes', 'government-schemes', 'PM schemes, subsidies, eligibility, benefits', '🏛', 703),
    ('Legal Advice & Consumer Rights', 'legal-advice-consumer-rights', 'FIRs, notices, consumer court, RTI', '⚖', 704),
    ('Traffic & Driving (RTO)', 'traffic-driving-rto', 'Driving licence, challans, vehicle registration', '🚗', 705),
    ('Property & Tenant Law', 'property-tenant-law', 'Rent agreements, disputes, registration', '🏚️', 706),
    ('Elections & Civic Issues', 'elections-civic-issues', 'Voter ID, municipal complaints, civic life', '🗳️', 707),
    ('Indian Railways Travel', 'indian-railways-travel', 'Bookings, tatkal, refunds, train info', '🛤️', 708),
    ('City Life & Relocation', 'city-life-relocation', 'Moving cities, cost of living, neighbourhoods', '🌆', 709),
    ('Village & Rural Life', 'village-rural-life', 'Rural livelihoods, panchayat, village issues', '🌾', 710),
    ('Agriculture & Farming', 'agriculture-farming', 'Crops, mandis, subsidies, modern farming', '🚜', 711),
    ('NRI Corner', 'nri-corner', 'NRI banking, taxation, returning to India', '🧳', 712),
    ('Festivals & Traditions', 'festivals-traditions', 'Festivals, rituals, cultural questions', '🪔', 713),
    ('Astrology & Vastu', 'astrology-vastu', 'Horoscopes, kundli, vastu queries', '🔮', 714),
    ('Regional: North India', 'regional-north-india', 'Delhi, UP, Punjab, Rajasthan and nearby', '🏔️', 715),
    ('Regional: South India', 'regional-south-india', 'Karnataka, TN, Kerala, AP, Telangana', '🌴', 716),
    ('Regional: East & Northeast', 'regional-east-northeast', 'Bengal, Odisha, Bihar, Northeast states', '🌅', 717),
    ('Regional: West India', 'regional-west-india', 'Maharashtra, Gujarat, Goa, MP', '🌊', 718),
    -- Travel (740s)
    ('Domestic Travel', 'domestic-travel', 'Destinations, itineraries, budget trips in India', '🧭', 741),
    ('International Travel', 'international-travel', 'Foreign trips, flight hacks, forex', '🌏', 742),
    ('Trekking & Adventure', 'trekking-adventure', 'Treks, camping, adventure sports', '⛰️', 743),
    ('Pilgrimage & Religious Travel', 'pilgrimage-religious-travel', 'Yatras, temple visits, routes and stays', '🛕', 744),
    ('Hotels & Stays', 'hotels-stays', 'Booking advice, homestays, reviews', '🛎️', 745),
    ('Solo & Budget Travel', 'solo-budget-travel', 'Traveling alone, backpacking, saving on trips', '🎒', 746),
    -- Entertainment & Sports (800s)
    ('Movies & OTT', 'movies-ott', 'Films, Netflix, Prime, recommendations', '🎬', 801),
    ('TV & Web Series', 'tv-web-series', 'Serials, web series, what to watch', '📺', 802),
    ('Music & Podcasts', 'music-podcasts', 'Songs, artists, playlists, podcasts', '🎧', 803),
    ('Gaming', 'gaming', 'PC, console, mobile games, esports', '🕹️', 804),
    ('Cricket', 'cricket', 'IPL, team India, techniques, analysis', '🏏', 805),
    ('Football', 'football', 'ISL, EPL, world football', '⚽', 806),
    ('Other Sports', 'other-sports', 'Badminton, kabaddi, hockey, athletics', '🏸', 807),
    ('Fantasy Sports', 'fantasy-sports', 'Dream11, fantasy leagues, strategies', '🏆', 808),
    ('Celebrities & Pop Culture', 'celebrities-pop-culture', 'Stars, gossip, fan discussions', '⭐', 809),
    ('Anime & Comics', 'anime-comics', 'Anime, manga, comics, fandoms', '🗾', 810),
    ('Memes & Fun', 'memes-fun', 'Light-hearted questions and humour', '😂', 811),
    ('Puzzles & Quizzes', 'puzzles-quizzes', 'Riddles, brain teasers, GK quizzes', '🧩', 812),
    -- Science & Society (900s)
    ('Science & Space', 'science-space', 'Physics, astronomy, ISRO, discoveries', '🔭', 901),
    ('Mathematics', 'mathematics', 'Math concepts, problem solving', '➗', 902),
    ('History & Culture', 'history-culture', 'Indian and world history, heritage', '🏺', 903),
    ('Geography & Environment', 'geography-environment', 'Places, climate, ecology, pollution', '🌎', 904),
    ('Current Affairs & News', 'current-affairs-news', 'What is happening and why it matters', '📰', 905),
    ('Politics & Governance', 'politics-governance', 'Policies, government, political discussion', '🏤', 906),
    ('Economy & Trade', 'economy-trade', 'Indian economy, budget, global trade', '🌐', 907),
    ('Philosophy & Ethics', 'philosophy-ethics', 'Big questions, moral dilemmas', '🤔', 908),
    ('Psychology & Human Behaviour', 'psychology-human-behaviour', 'Why people do what they do', '🧬', 909),
    ('Religion & Belief', 'religion-belief', 'Faith, scriptures, interfaith questions', '🙏', 910),
    ('Social Issues', 'social-issues', 'Gender, caste, inequality, social change', '🫂', 911),
    ('Environment & Sustainability', 'environment-sustainability', 'Climate action, recycling, green living', '♻️', 912),
    ('Automobiles & Bikes', 'automobiles-bikes', 'Cars, bikes, EVs, maintenance, buying', '🏍️', 913),
    ('Electric Vehicles', 'electric-vehicles', 'EV buying, charging, range, subsidies', '🔋', 914),
    ('DIY Electronics & Robotics', 'diy-electronics-robotics', 'Arduino, Raspberry Pi, robotics projects', '🤖', 915),
    ('Space & Defence Tech', 'space-defence-tech', 'ISRO missions, defence technology', '🚀', 916),
    ('Did You Know / Facts', 'did-you-know-facts', 'Interesting facts and explanations', '💡', 917),
    ('Opinions & Polls', 'opinions-polls', 'What do you think? Community opinions', '📊', 918),
    ('Ask Me Anything (AMA)', 'ask-me-anything', 'Community AMAs with experts and members', '🎤', 919),
    ('Site Feedback & Help', 'site-feedback-help', 'Questions about using PuchoNow itself', '🛟', 920),
    ('Interview Experiences', 'interview-experiences', 'Real interview stories and questions asked', '🗒️', 216),
    ('Salary & Negotiation', 'salary-negotiation', 'Pay scales, hikes, offer negotiation', '💸', 217),
    ('Study Tips & Motivation', 'study-tips-motivation', 'Time tables, focus, exam strategy', '⏰', 319),
    ('Coding Interviews & DSA', 'coding-interviews-dsa', 'Data structures, algorithms, LeetCode prep', '🧑‍🏫', 121),
    ('Open Source', 'open-source', 'Contributing, licenses, maintaining projects', '🌟', 122),
    ('Telegram & WhatsApp Help', 'telegram-whatsapp-help', 'Features, privacy, business use of messengers', '💬', 123),
    ('Social Media', 'social-media', 'Instagram, YouTube, X — growth and issues', '📢', 124),
    ('Email & Productivity Tools', 'email-productivity-tools', 'Gmail, Office, Notion, productivity apps', '📧', 125),
    ('Printers & Peripherals', 'printers-peripherals', 'Printers, keyboards, monitors, accessories', '🖨️', 126),
    ('Smart Home & IoT', 'smart-home-iot', 'Smart devices, automation, connected homes', '🏠', 127),
    ('Freshers & Campus Placement', 'freshers-campus-placement', 'First job, campus drives, aptitude tests', '🎯', 218),
    ('Side Projects & Portfolios', 'side-projects-portfolios', 'Building and showcasing your work', '🧱', 219),
    ('Exam Results & Counselling', 'exam-results-counselling', 'Results, cutoffs, seat allotment rounds', '📢', 320),
    ('Distance & Open Learning', 'distance-open-learning', 'IGNOU, open universities, part-time degrees', '📬', 321),
    ('Kids Education & Activities', 'kids-education-activities', 'Preschool, activities, learning at home', '🧸', 322),
    ('Senior Citizens', 'senior-citizens', 'Health, pension, digital help for elders', '🧓', 621),
    ('Grief & Emotional Support', 'grief-emotional-support', 'Loss, loneliness, difficult times', '🕊️', 622),
    ('Food & Restaurants', 'food-restaurants', 'Eating out, street food, food reviews', '🍽️', 623),
    ('Tea, Coffee & Beverages', 'tea-coffee-beverages', 'Brewing, cafes, recipes', '☕', 624),
    ('Startups: Funding & Legal', 'startups-funding-legal', 'Term sheets, ESOPs, compliance for founders', '📑', 220),
    -- E-commerce & Online Business (1000s)
    ('Amazon Selling', 'amazon-selling', 'FBA, listings, account health, Amazon.in seller help', '📦', 1001),
    ('Flipkart Selling', 'flipkart-selling', 'Flipkart seller hub, listings, payments', '🛒', 1002),
    ('Meesho & Reselling', 'meesho-reselling', 'Reselling apps, margins, supplier tips', '👜', 1003),
    ('Shopify & D2C Stores', 'shopify-d2c-stores', 'Building your own online store and brand', '🏬', 1004),
    ('WooCommerce & WordPress Shops', 'woocommerce-wordpress-shops', 'WordPress-based stores, plugins, themes', '🔌', 1005),
    ('Dropshipping', 'dropshipping', 'Suppliers, winning products, is it viable?', '🚢', 1006),
    ('Print on Demand', 'print-on-demand', 'Custom merch, POD platforms, designs', '👕', 1007),
    ('Product Sourcing & Wholesale', 'product-sourcing-wholesale', 'Manufacturers, IndiaMART, import from China', '🏭', 1008),
    ('Ecommerce Logistics & Shipping', 'ecommerce-logistics-shipping', 'Couriers, shipping rates, returns, RTO', '🚚', 1009),
    ('Ecommerce Payments & Gateways', 'ecommerce-payments-gateways', 'Razorpay, COD, settlements, chargebacks', '💳', 1010),
    ('Product Photography & Listings', 'product-photography-listings', 'Photos, titles, descriptions that convert', '📸', 1011),
    ('Marketplace Ads (PPC)', 'marketplace-ads-ppc', 'Amazon/Flipkart ads, ACOS, campaigns', '🎯', 1012),
    ('Ecommerce SEO & Traffic', 'ecommerce-seo-traffic', 'Ranking products, organic store traffic', '🔎', 1013),
    ('Social Commerce', 'social-commerce', 'Selling via Instagram, WhatsApp, Facebook', '🤳', 1014),
    ('ONDC & Government Ecommerce', 'ondc-government-ecommerce', 'ONDC network, GeM portal for sellers', '🏛️', 1015),
    ('Ecommerce GST & Compliance', 'ecommerce-gst-compliance', 'GST for sellers, invoicing, marketplace taxes', '🧾', 1016),
    ('Customer Service & Reviews', 'customer-service-reviews', 'Handling complaints, ratings, feedback', '⭐', 1017),
    ('Inventory & Order Management', 'inventory-order-management', 'Stock control, ERPs, multi-channel sync', '📋', 1018),
    ('Export & Cross-border Selling', 'export-cross-border-selling', 'Selling abroad, export documentation', '🌍', 1019),
    ('Ecommerce Analytics', 'ecommerce-analytics', 'Conversion rates, metrics, A/B testing', '📈', 1020),
    ('Grocery & Quick Commerce', 'grocery-quick-commerce', 'Blinkit, Zepto, Instamart selling and usage', '🥦', 1021),
    ('Fashion Ecommerce', 'fashion-ecommerce', 'Selling apparel online, Myntra, size charts', '👚', 1022),
    ('Handmade & Crafts Selling', 'handmade-crafts-selling', 'Etsy, handmade products, artisan sellers', '🧵', 1023),
    ('Digital Products & Courses', 'digital-products-courses', 'Selling ebooks, courses, templates online', '💾', 1024),
    ('Subscription & SaaS Business', 'subscription-saas-business', 'Recurring revenue, SaaS pricing, churn', '🔁', 1025),
    -- More Technology (1100s)
    ('WordPress & CMS', 'wordpress-cms', 'WordPress, themes, plugins, other CMSes', '📰', 1101),
    ('APIs & Integrations', 'apis-integrations', 'REST, webhooks, connecting services', '🔗', 1102),
    ('Testing & QA', 'testing-qa', 'Manual and automation testing, Selenium', '🧪', 1103),
    ('DevOps & CI/CD', 'devops-cicd', 'Docker, Kubernetes, pipelines, deployment', '🔄', 1104),
    ('Linux & Servers', 'linux-servers', 'Server admin, shell, self-hosting', '🖳', 1105),
    ('Web Hosting & Domains', 'web-hosting-domains', 'Shared hosting, VPS, DNS, SSL issues', '🌐', 1106),
    ('Chrome Extensions & Browsers', 'chrome-extensions-browsers', 'Browsers, extensions, browser issues', '🧩', 1107),
    ('Excel & Spreadsheets', 'excel-spreadsheets', 'Formulas, pivot tables, Google Sheets', '📗', 1108),
    ('PowerPoint & Presentations', 'powerpoint-presentations', 'Slides, design, presenting well', '📽️', 1109),
    ('Video Editing', 'video-editing', 'Premiere, DaVinci, CapCut, editing workflow', '🎞️', 1110),
    ('Graphic Design Tools', 'graphic-design-tools', 'Photoshop, Canva, Illustrator help', '🖌️', 1111),
    ('3D & Animation', '3d-animation', 'Blender, Maya, motion graphics', '🎭', 1112),
    ('AR/VR & Metaverse', 'ar-vr-metaverse', 'Augmented and virtual reality tech', '🥽', 1113),
    ('Drones', 'drones', 'Drone flying, rules in India, photography', '🛸', 1114),
    ('Tech News & Launches', 'tech-news-launches', 'New releases, updates, industry news', '🗞️', 1115),
    -- More Career & Business (1200s)
    ('Consulting & Professional Services', 'consulting-professional-services', 'Starting and running a practice', '💼', 1201),
    ('Real Estate Careers', 'real-estate-careers', 'Broking, RERA agents, property business', '🏢', 1202),
    ('Restaurant & Food Business', 'restaurant-food-business', 'Cloud kitchens, cafes, FSSAI, Zomato/Swiggy', '🍜', 1203),
    ('Franchise Business', 'franchise-business', 'Buying franchises, costs, evaluation', '🏪', 1204),
    ('Import Export Business', 'import-export-business', 'IEC code, trade, customs, logistics', '🚢', 1205),
    ('Manufacturing & Factory', 'manufacturing-factory', 'Setting up units, machinery, licenses', '🏭', 1206),
    ('Transport & Logistics Business', 'transport-logistics-business', 'Fleet, trucking, courier franchises', '🚛', 1207),
    ('Salon & Beauty Business', 'salon-beauty-business', 'Salons, parlours, beauty entrepreneurship', '💇', 1208),
    ('Pharmacy & Medical Business', 'pharmacy-medical-business', 'Medical stores, clinics, licenses', '💊', 1209),
    ('Coaching & EdTech Business', 'coaching-edtech-business', 'Running institutes, online academies', '🏫', 1210),
    ('Event Management Business', 'event-management-business', 'Events, catering, decoration business', '🎪', 1211),
    ('Travel Agency Business', 'travel-agency-business', 'Ticketing, packages, IATA, tourism business', '🧳', 1212),
    ('Dairy & Poultry Farming', 'dairy-poultry-farming', 'Dairy, poultry, fisheries as business', '🐄', 1213),
    ('Gig Economy & Delivery Work', 'gig-economy-delivery-work', 'Swiggy, Zomato, Uber, Ola partner questions', '🛵', 1214),
    ('Women Entrepreneurs', 'women-entrepreneurs', 'Schemes, funding and support for women founders', '👩‍💼', 1215),
    -- More Education (1300s)
    ('GATE & PSU Exams', 'gate-psu-exams', 'GATE preparation, PSU recruitment', '⚡', 1301),
    ('NET, SET & PhD', 'net-set-phd', 'UGC NET, research admissions, academia', '🎓', 1302),
    ('Nursing & Paramedical', 'nursing-paramedical', 'Nursing exams, courses, careers', '👩‍⚕️', 1303),
    ('Pharmacy Education', 'pharmacy-education', 'B.Pharm, D.Pharm, GPAT', '⚗️', 1304),
    ('Agriculture Education', 'agriculture-education', 'ICAR, BSc Agriculture, agri careers', '🌱', 1305),
    ('Hotel Management', 'hotel-management', 'NCHM JEE, hospitality careers', '🏨', 1306),
    ('Fashion & Design Education', 'fashion-design-education', 'NIFT, NID, design portfolios', '✂️', 1307),
    ('Mass Communication & Journalism', 'mass-communication-journalism', 'Media courses, journalism careers', '🎙️', 1308),
    ('Aviation & Merchant Navy', 'aviation-merchant-navy', 'Pilot training, cabin crew, marine careers', '✈️', 1309),
    ('Sports Careers & Education', 'sports-careers-education', 'Sports quota, physical education, coaching', '🏅', 1310),
    ('Skill India & ITI', 'skill-india-iti', 'ITI trades, PMKVY, vocational training', '🔩', 1311),
    ('Olympiads & Competitions', 'olympiads-competitions', 'Olympiads, hackathons, contests', '🥇', 1312),
    -- More Finance (1400s)
    ('Credit Cards', 'credit-cards', 'Best cards, rewards, annual fees, disputes', '💳', 1401),
    ('EPF & ESI', 'epf-esi', 'PF withdrawal, transfer, ESI benefits', '🗃️', 1402),
    ('Fixed Deposits & Small Savings', 'fixed-deposits-small-savings', 'FDs, RDs, post office schemes', '🏦', 1403),
    ('IPOs & Listings', 'ipos-listings', 'Applying for IPOs, GMP, allotment', '🔔', 1404),
    ('F&O and Derivatives', 'fo-derivatives', 'Futures, options strategies, risks', '📊', 1405),
    ('Financial Planning & FIRE', 'financial-planning-fire', 'Goal planning, early retirement, corpus', '🔥', 1406),
    ('Currency & Forex', 'currency-forex', 'Exchange rates, forex cards, remittances', '💱', 1407),
    ('Business Loans & MSME Finance', 'business-loans-msme-finance', 'Mudra, CGTMSE, working capital', '🏗️', 1408),
    -- More Lifestyle & Local (1500s)
    ('Interior Design & Decor', 'interior-design-decor', 'Home styling, furniture, budget decor', '🛋️', 1501),
    ('Cleaning & Organization', 'cleaning-organization', 'Home hacks, decluttering, maintenance', '🧹', 1502),
    ('Appliances & White Goods', 'appliances-white-goods', 'AC, fridge, washing machine advice and repair', '🧊', 1503),
    ('Water & Electricity Issues', 'water-electricity-issues', 'Bills, connections, RO systems, inverters', '💡', 1504),
    ('Society & Apartment Living', 'society-apartment-living', 'RWA, maintenance, society disputes', '🏢', 1505),
    ('Two-Wheelers & Scooters', 'two-wheelers-scooters', 'Bikes, scooters, mileage, servicing', '🛵', 1506),
    ('Public Transport & Metro', 'public-transport-metro', 'Metro, buses, cards, routes', '🚇', 1507),
    ('Postal & Courier Services', 'postal-courier-services', 'India Post, speed post, tracking issues', '📮', 1508),
    ('Mobile Recharge & Telecom', 'mobile-recharge-telecom', 'Jio, Airtel, Vi plans, porting, DTH', '📶', 1509),
    ('Banking Complaints & Ombudsman', 'banking-complaints-ombudsman', 'Disputes, ombudsman, grievance redressal', '🏛', 1510),
    ('Cyber Crime & Online Safety', 'cyber-crime-online-safety', 'Reporting cyber fraud, 1930 helpline, recovery', '👮', 1511),
    ('Matrimony & Arranged Marriage', 'matrimony-arranged-marriage', 'Matrimonial sites, rishta questions', '💍', 1512),
    ('Baby Names & Traditions', 'baby-names-traditions', 'Naming, ceremonies, customs', '🍼', 1513),
    ('Gifts & Occasions', 'gifts-occasions', 'Gift ideas for every budget and occasion', '🎁', 1514),
    ('Stationery & Books Buying', 'stationery-books-buying', 'Where to buy, textbooks, second-hand books', '📚', 1515),
    ('Second-hand & Refurbished', 'second-hand-refurbished', 'OLX, refurbished phones, used cars', '♻️', 1516),
    ('Ecommerce Returns & Refunds', 'ecommerce-returns-refunds', 'Buyer refund issues, replacement policies', '↩️', 1026),
    ('Affiliate Marketing', 'affiliate-marketing', 'Affiliate programs, commissions, disclosure', '🔗', 1027),
    ('Ecommerce Website Builders', 'ecommerce-website-builders', 'Dukaan, Wix, comparing store platforms', '🧱', 1028),
    ('B2B Ecommerce', 'b2b-ecommerce', 'Udaan, bulk selling, business buyers', '🏢', 1029),
    ('Festive & Seasonal Sales', 'festive-seasonal-sales', 'Big Billion Days, Prime Day, sale strategy', '🎉', 1030),
    ('Brand Building & Packaging', 'brand-building-packaging', 'Branding, trademarks, packaging design', '🎀', 1031),
    ('Recharge & Bill Payment Apps', 'recharge-bill-payment-apps', 'Paytm, PhonePe, GPay issues and cashback', '📲', 1517),
    ('Online Reviews & Ratings', 'online-reviews-ratings', 'Fake reviews, rating products honestly', '🌟', 1518);
