-- Expanded category catalog (~175 new). INSERT IGNORE: rows whose name/slug
-- already exist are skipped, so this is safe to run on any environment.
-- sort_order blocks: 100s tech, 200s career, 300s education, 400s finance,
-- 500s health, 600s lifestyle, 700s India/local, 800s entertainment & sports,
-- 900s science/society/misc. Existing 8 broad categories keep 1-99.
INSERT IGNORE INTO categories (name, slug, description, icon, sort_order) VALUES
    -- Technology (100s)
    ('Web Development', 'web-development', 'HTML, CSS, JavaScript, frameworks, full-stack', '🌐', 101),
    ('Mobile App Development', 'mobile-app-development', 'Android, iOS, Flutter, React Native', '📱', 102),
    ('Programming Languages', 'programming-languages', 'Python, Java, C++, PHP, Go and more', '⌨️', 103),
    ('Data Science & Analytics', 'data-science-analytics', 'Statistics, ML models, data visualization', '📊', 104),
    ('Artificial Intelligence', 'artificial-intelligence', 'AI tools, LLMs, prompt engineering, ML', '🤖', 105),
    ('Cybersecurity', 'cybersecurity', 'Online safety, hacking prevention, privacy', '🔐', 106),
    ('Cloud Computing', 'cloud-computing', 'AWS, Azure, GCP, hosting, DevOps', '☁️', 107),
    ('Databases', 'databases', 'SQL, NoSQL, database design and tuning', '🗄️', 108),
    ('Networking & Internet', 'networking-internet', 'WiFi, routers, ISPs, connectivity issues', '📡', 109),
    ('Computers & Laptops', 'computers-laptops', 'Buying advice, repairs, upgrades', '🖥️', 110),
    ('Smartphones & Gadgets', 'smartphones-gadgets', 'Phone comparisons, wearables, accessories', '📲', 111),
    ('Software & Apps', 'software-apps', 'App recommendations, troubleshooting, how-tos', '💿', 112),
    ('Operating Systems', 'operating-systems', 'Windows, macOS, Linux, Android, iOS', '🐧', 113),
    ('Game Development', 'game-development', 'Unity, Unreal, game design and publishing', '🎮', 114),
    ('Blockchain & Crypto Tech', 'blockchain-crypto-tech', 'Smart contracts, web3 development', '⛓️', 115),
    ('Tech Support & Troubleshooting', 'tech-support', 'Fix errors, crashes and device problems', '🛠️', 116),
    ('Gadget Buying Advice', 'gadget-buying-advice', 'Which one should I buy? Compare before you pay', '🛒', 117),
    ('SEO & Digital Tools', 'seo-digital-tools', 'Search rankings, analytics, webmaster tools', '🔍', 118),
    ('No-Code & Automation', 'no-code-automation', 'Zapier, n8n, website builders, workflows', '⚙️', 119),
    ('UI/UX Design', 'ui-ux-design', 'Interfaces, usability, Figma, product design', '🎯', 120),
    -- Career & Jobs (200s)
    ('Career Guidance', 'career-guidance', 'Choosing and switching career paths', '🧭', 201),
    ('Resume & Interviews', 'resume-interviews', 'CV reviews, interview prep, negotiations', '📄', 202),
    ('Government Jobs', 'government-jobs', 'Sarkari naukri, vacancies, selection process', '🏛️', 203),
    ('IT & Software Jobs', 'it-software-jobs', 'Tech hiring, placements, career growth', '👨‍💻', 204),
    ('Freelancing', 'freelancing', 'Finding clients, platforms, pricing your work', '🧑‍💻', 205),
    ('Work From Home', 'work-from-home', 'Remote jobs, online earning, home office', '🏡', 206),
    ('Internships', 'internships', 'Finding internships, stipends, experience letters', '🎓', 207),
    ('Workplace Advice', 'workplace-advice', 'Office politics, appraisals, HR issues', '🏢', 208),
    ('Business Ideas & Startups', 'business-ideas-startups', 'Validation, funding, incorporation', '🚀', 209),
    ('Small Business & MSME', 'small-business-msme', 'Shops, services, Udyam registration, growth', '🏪', 210),
    ('Marketing & Sales', 'marketing-sales', 'Digital marketing, ads, lead generation', '📣', 211),
    ('E-commerce & Selling Online', 'ecommerce-selling-online', 'Amazon, Flipkart, Meesho, D2C stores', '🛍️', 212),
    ('Content Creation', 'content-creation', 'YouTube, blogging, podcasting, monetization', '🎥', 213),
    ('Skilled Trades', 'skilled-trades', 'Electricians, plumbers, mechanics, technicians', '🔧', 214),
    ('Teaching & Coaching Careers', 'teaching-coaching-careers', 'Tutoring, coaching institutes, online teaching', '👩‍🏫', 215),
    -- Education & Exams (300s)
    ('UPSC & Civil Services', 'upsc-civil-services', 'IAS, IPS, state PCS preparation', '📜', 301),
    ('SSC & Banking Exams', 'ssc-banking-exams', 'SSC CGL, IBPS, SBI PO, RBI exams', '🏦', 302),
    ('JEE & Engineering Entrance', 'jee-engineering-entrance', 'JEE Main, Advanced, state CETs', '📐', 303),
    ('NEET & Medical Entrance', 'neet-medical-entrance', 'NEET UG/PG, AIIMS, medical admissions', '⚕️', 304),
    ('CAT & MBA Entrance', 'cat-mba-entrance', 'CAT, XAT, GMAT, B-school admissions', '📈', 305),
    ('Board Exams (10th & 12th)', 'board-exams', 'CBSE, ICSE, state boards, results', '📝', 306),
    ('College Admissions', 'college-admissions', 'Choosing colleges, cutoffs, counselling', '🏫', 307),
    ('Study Abroad', 'study-abroad', 'IELTS, TOEFL, GRE, university applications', '🌍', 308),
    ('Scholarships & Financial Aid', 'scholarships-financial-aid', 'Scholarships, education loans, fee waivers', '🎖️', 309),
    ('Online Courses & Certifications', 'online-courses-certifications', 'MOOCs, Coursera, Udemy, certificates worth it?', '🖱️', 310),
    ('School Homework Help', 'school-homework-help', 'Math, science and subject doubts', '✏️', 311),
    ('English & Communication', 'english-communication', 'Spoken English, writing, public speaking', '🗣️', 312),
    ('Languages Learning', 'languages-learning', 'Hindi, regional and foreign languages', '🈯', 313),
    ('Defence Exams (NDA/CDS)', 'defence-exams', 'NDA, CDS, AFCAT, Agniveer recruitment', '🎖', 314),
    ('Railway Exams', 'railway-exams', 'RRB NTPC, Group D, loco pilot exams', '🚆', 315),
    ('State Government Exams', 'state-government-exams', 'State PSCs, police, patwari, teacher eligibility', '🗺️', 316),
    ('Law Entrance & LLB', 'law-entrance-llb', 'CLAT, judiciary exams, law school', '⚖️', 317),
    ('CA, CS & CMA', 'ca-cs-cma', 'Chartered accountancy and company secretary path', '🧮', 318),
    -- Money & Finance (400s)
    ('Personal Finance', 'personal-finance', 'Budgeting, saving, money management', '💰', 401),
    ('Stock Market & Trading', 'stock-market-trading', 'Shares, F&O, technical analysis, brokers', '📉', 402),
    ('Mutual Funds & SIP', 'mutual-funds-sip', 'Fund selection, SIPs, portfolio review', '🪙', 403),
    ('Cryptocurrency Investing', 'cryptocurrency-investing', 'Bitcoin, exchanges, taxation on crypto', '₿', 404),
    ('Income Tax & GST', 'income-tax-gst', 'ITR filing, GST returns, tax saving', '🧾', 405),
    ('Banking & UPI', 'banking-upi', 'Accounts, UPI issues, net banking, KYC', '💳', 406),
    ('Loans & Credit', 'loans-credit', 'Home, personal, education loans, CIBIL score', '🏗️', 407),
    ('Insurance', 'insurance', 'Health, term, vehicle insurance and claims', '🛡️', 408),
    ('Retirement & Pension', 'retirement-pension', 'EPF, NPS, PPF, retirement planning', '👴', 409),
    ('Real Estate & Property', 'real-estate-property', 'Buying, renting, RERA, registration', '🏘️', 410),
    ('Gold & Commodities', 'gold-commodities', 'Gold schemes, sovereign bonds, silver', '🥇', 411),
    ('Online Earning & Side Income', 'online-earning-side-income', 'Legit ways to earn online, passive income', '💵', 412),
    ('Frauds & Scam Awareness', 'frauds-scam-awareness', 'Spot and report scams, recover from fraud', '🚨', 413),
    -- Health & Wellness (500s)
    ('General Health', 'general-health', 'Symptoms, first aid, when to see a doctor', '🏥', 501),
    ('Fitness & Exercise', 'fitness-exercise', 'Gym, home workouts, yoga, running', '🏋️', 502),
    ('Diet & Nutrition', 'diet-nutrition', 'Meal plans, weight management, supplements', '🥗', 503),
    ('Mental Health', 'mental-health', 'Stress, anxiety, therapy, self-care', '🧠', 504),
    ('Women''s Health', 'womens-health', 'Periods, PCOS, pregnancy, menopause', '👩', 505),
    ('Men''s Health', 'mens-health', 'Fitness, hormones, male-specific concerns', '👨', 506),
    ('Child Health & Parenting', 'child-health-parenting', 'Baby care, vaccinations, child development', '👶', 507),
    ('Skin & Hair Care', 'skin-hair-care', 'Dermatology, hair fall, skincare routines', '💆', 508),
    ('Dental Care', 'dental-care', 'Teeth, braces, oral hygiene', '🦷', 509),
    ('Eye & Vision Care', 'eye-vision-care', 'Eyesight, glasses, LASIK, eye strain', '👁️', 510),
    ('Ayurveda & Home Remedies', 'ayurveda-home-remedies', 'Traditional medicine, natural remedies', '🌿', 511),
    ('Chronic Conditions', 'chronic-conditions', 'Diabetes, BP, thyroid, long-term care', '📋', 512),
    ('Sleep & Recovery', 'sleep-recovery', 'Insomnia, sleep hygiene, rest', '😴', 513),
    ('Addiction & Deaddiction', 'addiction-deaddiction', 'Quitting smoking, alcohol, screen addiction', '🚭', 514),
    -- Lifestyle & Home (600s)
    ('Cooking & Recipes', 'cooking-recipes', 'Indian and world cuisine, kitchen tips', '🍳', 601),
    ('Home Improvement & DIY', 'home-improvement-diy', 'Repairs, renovation, interiors', '🔨', 602),
    ('Gardening & Plants', 'gardening-plants', 'Home gardens, terrace farming, plant care', '🪴', 603),
    ('Relationships & Dating', 'relationships-dating', 'Love, breakups, communication', '❤️', 604),
    ('Marriage & Family', 'marriage-family', 'Married life, in-laws, family dynamics', '👪', 605),
    ('Parenting & Kids', 'parenting-kids', 'Raising children, schooling decisions, teens', '🧒', 606),
    ('Weddings & Events', 'weddings-events', 'Wedding planning, budgets, ceremonies', '💒', 607),
    ('Fashion & Style', 'fashion-style', 'Outfits, trends, grooming', '👗', 608),
    ('Beauty & Makeup', 'beauty-makeup', 'Makeup techniques, products, tutorials', '💄', 609),
    ('Pets & Animal Care', 'pets-animal-care', 'Dogs, cats, pet food, vet advice', '🐕', 610),
    ('Shopping & Deals', 'shopping-deals', 'Best buys, sales, product experiences', '🏷️', 611),
    ('Personal Development', 'personal-development', 'Habits, productivity, confidence, discipline', '🌱', 612),
    ('Spirituality & Meditation', 'spirituality-meditation', 'Meditation, mindfulness, spiritual practice', '🕉️', 613),
    ('Etiquette & Social Skills', 'etiquette-social-skills', 'Social situations, manners, networking', '🤝', 614),
    ('Hobbies & Crafts', 'hobbies-crafts', 'Art, collecting, model making, crafts', '🧶', 615),
    ('Books & Reading', 'books-reading', 'Recommendations, reviews, reading habits', '📖', 616),
    ('Photography', 'photography', 'Cameras, composition, editing, phone photography', '📷', 617),
    ('Writing & Blogging', 'writing-blogging', 'Creative writing, blogging, publishing', '✍️', 618),
    ('Music & Instruments', 'music-instruments', 'Learning instruments, singing, production', '🎸', 619),
    ('Dance & Performing Arts', 'dance-performing-arts', 'Dance forms, theatre, performance', '💃', 620),
    -- India & Local (700s)
    ('Aadhaar, PAN & Documents', 'aadhaar-pan-documents', 'ID cards, corrections, linking, DigiLocker', '🪪', 701),
    ('Passport & Visa', 'passport-visa', 'Passport application, visas, immigration', '🛂', 702),
    ('Government Schemes', 'government-schemes', 'PM schemes, subsidies, eligibility, benefits', '🏛', 703),
    ('Legal Advice & Consumer Rights', 'legal-advice-consumer-rights', 'FIRs, notices, consumer court, RTI', '⚖', 704),
    ('Traffic & Driving (RTO)', 'traffic-driving-rto', 'Driving licence, challans, vehicle registration', '🚗', 705),
    ('Property & Tenant Law', 'property-tenant-law', 'Rent agreements, disputes, registration', '🏚️', 706),
    ('Elections & Civic Issues', 'elections-civic-issues', 'Voter ID, municipal complaints, civic life', '🗳️', 707),
    ('Indian Railways Travel', 'indian-railways-travel', 'Bookings, tatkal, refunds, train info', '🛤️', 708),
    ('City Life & Relocation', 'city-life-relocation', 'Moving cities, cost of living, neighbourhoods', '🌆', 709),
    ('Village & Rural Life', 'village-rural-life', 'Rural livelihoods, panchayat, village issues', '🌾', 710),
    ('Agriculture & Farming', 'agriculture-farming', 'Crops, mandis, subsidies, modern farming', '🚜', 711),
    ('NRI Corner', 'nri-corner', 'NRI banking, taxation, returning to India', '🧳', 712),
    ('Festivals & Traditions', 'festivals-traditions', 'Festivals, rituals, cultural questions', '🪔', 713),
    ('Astrology & Vastu', 'astrology-vastu', 'Horoscopes, kundli, vastu queries', '🔮', 714),
    ('Regional: North India', 'regional-north-india', 'Delhi, UP, Punjab, Rajasthan and nearby', '🏔️', 715),
    ('Regional: South India', 'regional-south-india', 'Karnataka, TN, Kerala, AP, Telangana', '🌴', 716),
    ('Regional: East & Northeast', 'regional-east-northeast', 'Bengal, Odisha, Bihar, Northeast states', '🌅', 717),
    ('Regional: West India', 'regional-west-india', 'Maharashtra, Gujarat, Goa, MP', '🌊', 718),
    -- Travel (740s)
    ('Domestic Travel', 'domestic-travel', 'Destinations, itineraries, budget trips in India', '🧭', 741),
    ('International Travel', 'international-travel', 'Foreign trips, flight hacks, forex', '🌏', 742),
    ('Trekking & Adventure', 'trekking-adventure', 'Treks, camping, adventure sports', '⛰️', 743),
    ('Pilgrimage & Religious Travel', 'pilgrimage-religious-travel', 'Yatras, temple visits, routes and stays', '🛕', 744),
    ('Hotels & Stays', 'hotels-stays', 'Booking advice, homestays, reviews', '🛎️', 745),
    ('Solo & Budget Travel', 'solo-budget-travel', 'Traveling alone, backpacking, saving on trips', '🎒', 746),
    -- Entertainment & Sports (800s)
    ('Movies & OTT', 'movies-ott', 'Films, Netflix, Prime, recommendations', '🎬', 801),
    ('TV & Web Series', 'tv-web-series', 'Serials, web series, what to watch', '📺', 802),
    ('Music & Podcasts', 'music-podcasts', 'Songs, artists, playlists, podcasts', '🎧', 803),
    ('Gaming', 'gaming', 'PC, console, mobile games, esports', '🕹️', 804),
    ('Cricket', 'cricket', 'IPL, team India, techniques, analysis', '🏏', 805),
    ('Football', 'football', 'ISL, EPL, world football', '⚽', 806),
    ('Other Sports', 'other-sports', 'Badminton, kabaddi, hockey, athletics', '🏸', 807),
    ('Fantasy Sports', 'fantasy-sports', 'Dream11, fantasy leagues, strategies', '🏆', 808),
    ('Celebrities & Pop Culture', 'celebrities-pop-culture', 'Stars, gossip, fan discussions', '⭐', 809),
    ('Anime & Comics', 'anime-comics', 'Anime, manga, comics, fandoms', '🗾', 810),
    ('Memes & Fun', 'memes-fun', 'Light-hearted questions and humour', '😂', 811),
    ('Puzzles & Quizzes', 'puzzles-quizzes', 'Riddles, brain teasers, GK quizzes', '🧩', 812),
    -- Science & Society (900s)
    ('Science & Space', 'science-space', 'Physics, astronomy, ISRO, discoveries', '🔭', 901),
    ('Mathematics', 'mathematics', 'Math concepts, problem solving', '➗', 902),
    ('History & Culture', 'history-culture', 'Indian and world history, heritage', '🏺', 903),
    ('Geography & Environment', 'geography-environment', 'Places, climate, ecology, pollution', '🌎', 904),
    ('Current Affairs & News', 'current-affairs-news', 'What is happening and why it matters', '📰', 905),
    ('Politics & Governance', 'politics-governance', 'Policies, government, political discussion', '🏤', 906),
    ('Economy & Trade', 'economy-trade', 'Indian economy, budget, global trade', '🌐', 907),
    ('Philosophy & Ethics', 'philosophy-ethics', 'Big questions, moral dilemmas', '🤔', 908),
    ('Psychology & Human Behaviour', 'psychology-human-behaviour', 'Why people do what they do', '🧬', 909),
    ('Religion & Belief', 'religion-belief', 'Faith, scriptures, interfaith questions', '🙏', 910),
    ('Social Issues', 'social-issues', 'Gender, caste, inequality, social change', '🫂', 911),
    ('Environment & Sustainability', 'environment-sustainability', 'Climate action, recycling, green living', '♻️', 912),
    ('Automobiles & Bikes', 'automobiles-bikes', 'Cars, bikes, EVs, maintenance, buying', '🏍️', 913),
    ('Electric Vehicles', 'electric-vehicles', 'EV buying, charging, range, subsidies', '🔋', 914),
    ('DIY Electronics & Robotics', 'diy-electronics-robotics', 'Arduino, Raspberry Pi, robotics projects', '🤖', 915),
    ('Space & Defence Tech', 'space-defence-tech', 'ISRO missions, defence technology', '🚀', 916),
    ('Did You Know / Facts', 'did-you-know-facts', 'Interesting facts and explanations', '💡', 917),
    ('Opinions & Polls', 'opinions-polls', 'What do you think? Community opinions', '📊', 918),
    ('Ask Me Anything (AMA)', 'ask-me-anything', 'Community AMAs with experts and members', '🎤', 919),
    ('Site Feedback & Help', 'site-feedback-help', 'Questions about using PuchoNow itself', '🛟', 920),
    ('Interview Experiences', 'interview-experiences', 'Real interview stories and questions asked', '🗒️', 216),
    ('Salary & Negotiation', 'salary-negotiation', 'Pay scales, hikes, offer negotiation', '💸', 217),
    ('Study Tips & Motivation', 'study-tips-motivation', 'Time tables, focus, exam strategy', '⏰', 319),
    ('Coding Interviews & DSA', 'coding-interviews-dsa', 'Data structures, algorithms, LeetCode prep', '🧑‍🏫', 121),
    ('Open Source', 'open-source', 'Contributing, licenses, maintaining projects', '🌟', 122),
    ('Telegram & WhatsApp Help', 'telegram-whatsapp-help', 'Features, privacy, business use of messengers', '💬', 123),
    ('Social Media', 'social-media', 'Instagram, YouTube, X — growth and issues', '📢', 124),
    ('Email & Productivity Tools', 'email-productivity-tools', 'Gmail, Office, Notion, productivity apps', '📧', 125),
    ('Printers & Peripherals', 'printers-peripherals', 'Printers, keyboards, monitors, accessories', '🖨️', 126),
    ('Smart Home & IoT', 'smart-home-iot', 'Smart devices, automation, connected homes', '🏠', 127),
    ('Freshers & Campus Placement', 'freshers-campus-placement', 'First job, campus drives, aptitude tests', '🎯', 218),
    ('Side Projects & Portfolios', 'side-projects-portfolios', 'Building and showcasing your work', '🧱', 219),
    ('Exam Results & Counselling', 'exam-results-counselling', 'Results, cutoffs, seat allotment rounds', '📢', 320),
    ('Distance & Open Learning', 'distance-open-learning', 'IGNOU, open universities, part-time degrees', '📬', 321),
    ('Kids Education & Activities', 'kids-education-activities', 'Preschool, activities, learning at home', '🧸', 322),
    ('Senior Citizens', 'senior-citizens', 'Health, pension, digital help for elders', '🧓', 621),
    ('Grief & Emotional Support', 'grief-emotional-support', 'Loss, loneliness, difficult times', '🕊️', 622),
    ('Food & Restaurants', 'food-restaurants', 'Eating out, street food, food reviews', '🍽️', 623),
    ('Tea, Coffee & Beverages', 'tea-coffee-beverages', 'Brewing, cafes, recipes', '☕', 624),
    ('Startups: Funding & Legal', 'startups-funding-legal', 'Term sheets, ESOPs, compliance for founders', '📑', 220),
    -- E-commerce & Online Business (1000s)
    ('Amazon Selling', 'amazon-selling', 'FBA, listings, account health, Amazon.in seller help', '📦', 1001),
    ('Flipkart Selling', 'flipkart-selling', 'Flipkart seller hub, listings, payments', '🛒', 1002),
    ('Meesho & Reselling', 'meesho-reselling', 'Reselling apps, margins, supplier tips', '👜', 1003),
    ('Shopify & D2C Stores', 'shopify-d2c-stores', 'Building your own online store and brand', '🏬', 1004),
    ('WooCommerce & WordPress Shops', 'woocommerce-wordpress-shops', 'WordPress-based stores, plugins, themes', '🔌', 1005),
    ('Dropshipping', 'dropshipping', 'Suppliers, winning products, is it viable?', '🚢', 1006),
    ('Print on Demand', 'print-on-demand', 'Custom merch, POD platforms, designs', '👕', 1007),
    ('Product Sourcing & Wholesale', 'product-sourcing-wholesale', 'Manufacturers, IndiaMART, import from China', '🏭', 1008),
    ('Ecommerce Logistics & Shipping', 'ecommerce-logistics-shipping', 'Couriers, shipping rates, returns, RTO', '🚚', 1009),
    ('Ecommerce Payments & Gateways', 'ecommerce-payments-gateways', 'Razorpay, COD, settlements, chargebacks', '💳', 1010),
    ('Product Photography & Listings', 'product-photography-listings', 'Photos, titles, descriptions that convert', '📸', 1011),
    ('Marketplace Ads (PPC)', 'marketplace-ads-ppc', 'Amazon/Flipkart ads, ACOS, campaigns', '🎯', 1012),
    ('Ecommerce SEO & Traffic', 'ecommerce-seo-traffic', 'Ranking products, organic store traffic', '🔎', 1013),
    ('Social Commerce', 'social-commerce', 'Selling via Instagram, WhatsApp, Facebook', '🤳', 1014),
    ('ONDC & Government Ecommerce', 'ondc-government-ecommerce', 'ONDC network, GeM portal for sellers', '🏛️', 1015),
    ('Ecommerce GST & Compliance', 'ecommerce-gst-compliance', 'GST for sellers, invoicing, marketplace taxes', '🧾', 1016),
    ('Customer Service & Reviews', 'customer-service-reviews', 'Handling complaints, ratings, feedback', '⭐', 1017),
    ('Inventory & Order Management', 'inventory-order-management', 'Stock control, ERPs, multi-channel sync', '📋', 1018),
    ('Export & Cross-border Selling', 'export-cross-border-selling', 'Selling abroad, export documentation', '🌍', 1019),
    ('Ecommerce Analytics', 'ecommerce-analytics', 'Conversion rates, metrics, A/B testing', '📈', 1020),
    ('Grocery & Quick Commerce', 'grocery-quick-commerce', 'Blinkit, Zepto, Instamart selling and usage', '🥦', 1021),
    ('Fashion Ecommerce', 'fashion-ecommerce', 'Selling apparel online, Myntra, size charts', '👚', 1022),
    ('Handmade & Crafts Selling', 'handmade-crafts-selling', 'Etsy, handmade products, artisan sellers', '🧵', 1023),
    ('Digital Products & Courses', 'digital-products-courses', 'Selling ebooks, courses, templates online', '💾', 1024),
    ('Subscription & SaaS Business', 'subscription-saas-business', 'Recurring revenue, SaaS pricing, churn', '🔁', 1025),
    -- More Technology (1100s)
    ('WordPress & CMS', 'wordpress-cms', 'WordPress, themes, plugins, other CMSes', '📰', 1101),
    ('APIs & Integrations', 'apis-integrations', 'REST, webhooks, connecting services', '🔗', 1102),
    ('Testing & QA', 'testing-qa', 'Manual and automation testing, Selenium', '🧪', 1103),
    ('DevOps & CI/CD', 'devops-cicd', 'Docker, Kubernetes, pipelines, deployment', '🔄', 1104),
    ('Linux & Servers', 'linux-servers', 'Server admin, shell, self-hosting', '🖳', 1105),
    ('Web Hosting & Domains', 'web-hosting-domains', 'Shared hosting, VPS, DNS, SSL issues', '🌐', 1106),
    ('Chrome Extensions & Browsers', 'chrome-extensions-browsers', 'Browsers, extensions, browser issues', '🧩', 1107),
    ('Excel & Spreadsheets', 'excel-spreadsheets', 'Formulas, pivot tables, Google Sheets', '📗', 1108),
    ('PowerPoint & Presentations', 'powerpoint-presentations', 'Slides, design, presenting well', '📽️', 1109),
    ('Video Editing', 'video-editing', 'Premiere, DaVinci, CapCut, editing workflow', '🎞️', 1110),
    ('Graphic Design Tools', 'graphic-design-tools', 'Photoshop, Canva, Illustrator help', '🖌️', 1111),
    ('3D & Animation', '3d-animation', 'Blender, Maya, motion graphics', '🎭', 1112),
    ('AR/VR & Metaverse', 'ar-vr-metaverse', 'Augmented and virtual reality tech', '🥽', 1113),
    ('Drones', 'drones', 'Drone flying, rules in India, photography', '🛸', 1114),
    ('Tech News & Launches', 'tech-news-launches', 'New releases, updates, industry news', '🗞️', 1115),
    -- More Career & Business (1200s)
    ('Consulting & Professional Services', 'consulting-professional-services', 'Starting and running a practice', '💼', 1201),
    ('Real Estate Careers', 'real-estate-careers', 'Broking, RERA agents, property business', '🏢', 1202),
    ('Restaurant & Food Business', 'restaurant-food-business', 'Cloud kitchens, cafes, FSSAI, Zomato/Swiggy', '🍜', 1203),
    ('Franchise Business', 'franchise-business', 'Buying franchises, costs, evaluation', '🏪', 1204),
    ('Import Export Business', 'import-export-business', 'IEC code, trade, customs, logistics', '🚢', 1205),
    ('Manufacturing & Factory', 'manufacturing-factory', 'Setting up units, machinery, licenses', '🏭', 1206),
    ('Transport & Logistics Business', 'transport-logistics-business', 'Fleet, trucking, courier franchises', '🚛', 1207),
    ('Salon & Beauty Business', 'salon-beauty-business', 'Salons, parlours, beauty entrepreneurship', '💇', 1208),
    ('Pharmacy & Medical Business', 'pharmacy-medical-business', 'Medical stores, clinics, licenses', '💊', 1209),
    ('Coaching & EdTech Business', 'coaching-edtech-business', 'Running institutes, online academies', '🏫', 1210),
    ('Event Management Business', 'event-management-business', 'Events, catering, decoration business', '🎪', 1211),
    ('Travel Agency Business', 'travel-agency-business', 'Ticketing, packages, IATA, tourism business', '🧳', 1212),
    ('Dairy & Poultry Farming', 'dairy-poultry-farming', 'Dairy, poultry, fisheries as business', '🐄', 1213),
    ('Gig Economy & Delivery Work', 'gig-economy-delivery-work', 'Swiggy, Zomato, Uber, Ola partner questions', '🛵', 1214),
    ('Women Entrepreneurs', 'women-entrepreneurs', 'Schemes, funding and support for women founders', '👩‍💼', 1215),
    -- More Education (1300s)
    ('GATE & PSU Exams', 'gate-psu-exams', 'GATE preparation, PSU recruitment', '⚡', 1301),
    ('NET, SET & PhD', 'net-set-phd', 'UGC NET, research admissions, academia', '🎓', 1302),
    ('Nursing & Paramedical', 'nursing-paramedical', 'Nursing exams, courses, careers', '👩‍⚕️', 1303),
    ('Pharmacy Education', 'pharmacy-education', 'B.Pharm, D.Pharm, GPAT', '⚗️', 1304),
    ('Agriculture Education', 'agriculture-education', 'ICAR, BSc Agriculture, agri careers', '🌱', 1305),
    ('Hotel Management', 'hotel-management', 'NCHM JEE, hospitality careers', '🏨', 1306),
    ('Fashion & Design Education', 'fashion-design-education', 'NIFT, NID, design portfolios', '✂️', 1307),
    ('Mass Communication & Journalism', 'mass-communication-journalism', 'Media courses, journalism careers', '🎙️', 1308),
    ('Aviation & Merchant Navy', 'aviation-merchant-navy', 'Pilot training, cabin crew, marine careers', '✈️', 1309),
    ('Sports Careers & Education', 'sports-careers-education', 'Sports quota, physical education, coaching', '🏅', 1310),
    ('Skill India & ITI', 'skill-india-iti', 'ITI trades, PMKVY, vocational training', '🔩', 1311),
    ('Olympiads & Competitions', 'olympiads-competitions', 'Olympiads, hackathons, contests', '🥇', 1312),
    -- More Finance (1400s)
    ('Credit Cards', 'credit-cards', 'Best cards, rewards, annual fees, disputes', '💳', 1401),
    ('EPF & ESI', 'epf-esi', 'PF withdrawal, transfer, ESI benefits', '🗃️', 1402),
    ('Fixed Deposits & Small Savings', 'fixed-deposits-small-savings', 'FDs, RDs, post office schemes', '🏦', 1403),
    ('IPOs & Listings', 'ipos-listings', 'Applying for IPOs, GMP, allotment', '🔔', 1404),
    ('F&O and Derivatives', 'fo-derivatives', 'Futures, options strategies, risks', '📊', 1405),
    ('Financial Planning & FIRE', 'financial-planning-fire', 'Goal planning, early retirement, corpus', '🔥', 1406),
    ('Currency & Forex', 'currency-forex', 'Exchange rates, forex cards, remittances', '💱', 1407),
    ('Business Loans & MSME Finance', 'business-loans-msme-finance', 'Mudra, CGTMSE, working capital', '🏗️', 1408),
    -- More Lifestyle & Local (1500s)
    ('Interior Design & Decor', 'interior-design-decor', 'Home styling, furniture, budget decor', '🛋️', 1501),
    ('Cleaning & Organization', 'cleaning-organization', 'Home hacks, decluttering, maintenance', '🧹', 1502),
    ('Appliances & White Goods', 'appliances-white-goods', 'AC, fridge, washing machine advice and repair', '🧊', 1503),
    ('Water & Electricity Issues', 'water-electricity-issues', 'Bills, connections, RO systems, inverters', '💡', 1504),
    ('Society & Apartment Living', 'society-apartment-living', 'RWA, maintenance, society disputes', '🏢', 1505),
    ('Two-Wheelers & Scooters', 'two-wheelers-scooters', 'Bikes, scooters, mileage, servicing', '🛵', 1506),
    ('Public Transport & Metro', 'public-transport-metro', 'Metro, buses, cards, routes', '🚇', 1507),
    ('Postal & Courier Services', 'postal-courier-services', 'India Post, speed post, tracking issues', '📮', 1508),
    ('Mobile Recharge & Telecom', 'mobile-recharge-telecom', 'Jio, Airtel, Vi plans, porting, DTH', '📶', 1509),
    ('Banking Complaints & Ombudsman', 'banking-complaints-ombudsman', 'Disputes, ombudsman, grievance redressal', '🏛', 1510),
    ('Cyber Crime & Online Safety', 'cyber-crime-online-safety', 'Reporting cyber fraud, 1930 helpline, recovery', '👮', 1511),
    ('Matrimony & Arranged Marriage', 'matrimony-arranged-marriage', 'Matrimonial sites, rishta questions', '💍', 1512),
    ('Baby Names & Traditions', 'baby-names-traditions', 'Naming, ceremonies, customs', '🍼', 1513),
    ('Gifts & Occasions', 'gifts-occasions', 'Gift ideas for every budget and occasion', '🎁', 1514),
    ('Stationery & Books Buying', 'stationery-books-buying', 'Where to buy, textbooks, second-hand books', '📚', 1515),
    ('Second-hand & Refurbished', 'second-hand-refurbished', 'OLX, refurbished phones, used cars', '♻️', 1516),
    ('Ecommerce Returns & Refunds', 'ecommerce-returns-refunds', 'Buyer refund issues, replacement policies', '↩️', 1026),
    ('Affiliate Marketing', 'affiliate-marketing', 'Affiliate programs, commissions, disclosure', '🔗', 1027),
    ('Ecommerce Website Builders', 'ecommerce-website-builders', 'Dukaan, Wix, comparing store platforms', '🧱', 1028),
    ('B2B Ecommerce', 'b2b-ecommerce', 'Udaan, bulk selling, business buyers', '🏢', 1029),
    ('Festive & Seasonal Sales', 'festive-seasonal-sales', 'Big Billion Days, Prime Day, sale strategy', '🎉', 1030),
    ('Brand Building & Packaging', 'brand-building-packaging', 'Branding, trademarks, packaging design', '🎀', 1031),
    ('Recharge & Bill Payment Apps', 'recharge-bill-payment-apps', 'Paytm, PhonePe, GPay issues and cashback', '📲', 1517),
    ('Online Reviews & Ratings', 'online-reviews-ratings', 'Fake reviews, rating products honestly', '🌟', 1518),
    -- City communities (1600s)
    ('Delhi NCR', 'delhi-ncr', 'Life, jobs and questions in Delhi, Noida, Gurugram', '🏙️', 1601),
    ('Mumbai', 'mumbai', 'Local life, housing, transport in Mumbai', '🌉', 1602),
    ('Bengaluru', 'bengaluru', 'Tech city living, traffic, PGs, startups', '🌳', 1603),
    ('Hyderabad', 'hyderabad', 'Local questions from Hyderabad and Secunderabad', '🕌', 1604),
    ('Chennai', 'chennai', 'Living and working in Chennai', '🏖️', 1605),
    ('Kolkata', 'kolkata', 'Local life and questions from Kolkata', '🌁', 1606),
    ('Pune', 'pune', 'Students, IT parks and life in Pune', '⛰️', 1607),
    ('Ahmedabad', 'ahmedabad', 'Local questions from Ahmedabad and Gandhinagar', '🏛️', 1608),
    ('Jaipur', 'jaipur', 'Pink city life, tourism, local help', '🏰', 1609),
    ('Lucknow', 'lucknow', 'Local life and questions from Lucknow', '🍢', 1610),
    ('Chandigarh & Tricity', 'chandigarh-tricity', 'Chandigarh, Mohali, Panchkula questions', '🌹', 1611),
    ('Indore & Bhopal', 'indore-bhopal', 'MP''s big cities — local questions', '🍽️', 1612),
    ('Patna', 'patna', 'Local life and questions from Patna', '🌉', 1613),
    ('Ranchi & Jamshedpur', 'ranchi-jamshedpur', 'Jharkhand cities — local questions', '🏞️', 1614),
    ('Bhubaneswar & Cuttack', 'bhubaneswar-cuttack', 'Odisha twin cities — local questions', '🛕', 1615),
    ('Guwahati & Northeast Cities', 'guwahati-northeast-cities', 'Northeast urban life and travel', '🦏', 1616),
    ('Kochi & Trivandrum', 'kochi-trivandrum', 'Kerala cities — local questions', '🛶', 1617),
    ('Coimbatore & Madurai', 'coimbatore-madurai', 'Tamil Nadu cities beyond Chennai', '🏭', 1618),
    ('Nagpur', 'nagpur', 'Local life and questions from Nagpur', '🍊', 1619),
    ('Surat & Vadodara', 'surat-vadodara', 'Gujarat business cities — local questions', '💎', 1620),
    ('Varanasi & Prayagraj', 'varanasi-prayagraj', 'Culture, travel and local life in UP east', '🕉', 1621),
    ('Visakhapatnam & Vijayawada', 'visakhapatnam-vijayawada', 'Andhra cities — local questions', '⚓', 1622),
    ('Kanpur & Agra', 'kanpur-agra', 'UP industrial and heritage cities', '🕍', 1623),
    ('Dehradun & Uttarakhand Towns', 'dehradun-uttarakhand-towns', 'Hill state city life and relocation', '🌲', 1624),
    ('Goa Living', 'goa-living', 'Living, working and settling in Goa', '🏝️', 1625),
    -- Programming languages (1700s)
    ('Python', 'python', 'Python programming, scripts, libraries', '🐍', 1701),
    ('JavaScript', 'javascript', 'JS language, browser APIs, tooling', '🟨', 1702),
    ('Java', 'java', 'Core Java, JVM, enterprise development', '☕', 1703),
    ('PHP', 'php', 'PHP language, Composer, performance', '🐘', 1704),
    ('C & C++', 'c-cpp', 'Systems programming, competitive coding', '🔷', 1705),
    ('C# & .NET', 'csharp-dotnet', '.NET ecosystem, ASP.NET, desktop apps', '🟪', 1706),
    ('Go (Golang)', 'golang', 'Go language, concurrency, services', '🐹', 1707),
    ('Rust', 'rust', 'Rust language, memory safety, tooling', '🦀', 1708),
    ('Kotlin', 'kotlin', 'Kotlin for Android and backend', '🟧', 1709),
    ('Swift & iOS', 'swift-ios', 'Swift language, iOS app development', '🍎', 1710),
    ('TypeScript', 'typescript', 'Types, tsconfig, migration from JS', '🔵', 1711),
    ('R & Data Tools', 'r-data-tools', 'R language, statistics tooling', '📉', 1712),
    ('React', 'react', 'React, hooks, state management', '⚛️', 1713),
    ('Angular', 'angular', 'Angular framework questions', '🅰️', 1714),
    ('Vue & Svelte', 'vue-svelte', 'Vue, Nuxt, Svelte ecosystems', '💚', 1715),
    ('Node.js', 'nodejs', 'Node runtime, Express, npm', '🟩', 1716),
    ('Laravel', 'laravel', 'Laravel framework, Eloquent, Livewire', '🔺', 1717),
    ('Django & Flask', 'django-flask', 'Python web frameworks', '🎸', 1718),
    ('Spring Boot', 'spring-boot', 'Java Spring ecosystem', '🍃', 1719),
    ('Flutter', 'flutter', 'Flutter and Dart cross-platform apps', '🐦', 1720),
    -- School & college subjects (1800s)
    ('Physics', 'physics', 'Concepts, numericals, doubts', '🧲', 1801),
    ('Chemistry', 'chemistry', 'Organic, inorganic, physical chemistry', '⚗️', 1802),
    ('Biology', 'biology', 'Botany, zoology, human physiology', '🧫', 1803),
    ('Economics', 'economics', 'Micro, macro, Indian economics', '📊', 1804),
    ('Accountancy', 'accountancy', 'Accounts, journal entries, balance sheets', '📒', 1805),
    ('Business Studies', 'business-studies', 'BST concepts, case studies', '🏢', 1806),
    ('Political Science', 'political-science', 'Polity, constitution, theory', '🏛', 1807),
    ('Sociology & Humanities', 'sociology-humanities', 'Sociology, psychology as subjects', '👥', 1808),
    ('Computer Science (Subject)', 'computer-science-subject', 'CS/IP school and college syllabus', '💾', 1809),
    ('Statistics & Probability', 'statistics-probability', 'Stats concepts and problems', '🎲', 1810),
    ('Geography (Subject)', 'geography-subject', 'Physical, human and Indian geography', '🗺', 1811),
    ('Hindi & Sanskrit', 'hindi-sanskrit', 'Grammar, literature, translations', '📜', 1812),
    -- Health specifics (1850s)
    ('Yoga & Pranayama', 'yoga-pranayama', 'Asanas, breathing, yoga therapy', '🧘', 1851),
    ('Cardiac Health', 'cardiac-health', 'Heart health, BP, cholesterol', '❤️‍🩹', 1852),
    ('Orthopedics & Joint Pain', 'orthopedics-joint-pain', 'Back pain, knees, bones, posture', '🦴', 1853),
    ('ENT & Allergies', 'ent-allergies', 'Ear, nose, throat, sinus, allergies', '👂', 1854),
    ('Digestion & Gut Health', 'digestion-gut-health', 'Acidity, IBS, gut problems', '🫁', 1855),
    ('Physiotherapy & Rehab', 'physiotherapy-rehab', 'Recovery, exercises, injury rehab', '🤸', 1856),
    ('Cancer Care & Support', 'cancer-care-support', 'Treatment journeys, caregiving, support', '🎗️', 1857),
    ('Infections & Fever', 'infections-fever', 'Viral fevers, dengue, infections', '🌡️', 1858),
    ('Vaccines & Immunization', 'vaccines-immunization', 'Vaccination schedules and doubts', '💉', 1859),
    ('First Aid & Emergency', 'first-aid-emergency', 'Emergency response, ambulances, ER', '🚑', 1860),
    -- Food specifics (1900s)
    ('Vegetarian & Vegan', 'vegetarian-vegan', 'Plant-based cooking and nutrition', '🥬', 1901),
    ('Baking & Desserts', 'baking-desserts', 'Cakes, breads, Indian sweets', '🎂', 1902),
    ('Regional Cuisines', 'regional-cuisines', 'Punjabi, South Indian, Bengali & more', '🍛', 1903),
    ('Snacks & Fast Food', 'snacks-fast-food', 'Quick bites, chaat, homemade snacks', '🍟', 1904),
    ('Healthy Cooking', 'healthy-cooking', 'Low oil, high protein, diabetic-friendly', '🥙', 1905),
    ('Spices & Ingredients', 'spices-ingredients', 'Masalas, substitutes, sourcing', '🌶️', 1906),
    ('Kitchen Appliances', 'kitchen-appliances', 'Mixers, air fryers, chimneys, cookware', '🍲', 1907),
    ('Tiffin & Meal Prep', 'tiffin-meal-prep', 'Lunchbox ideas, batch cooking', '🍱', 1908),
    ('Street Food', 'street-food', 'Street eats, hygiene, recreating at home', '🌮', 1909),
    ('Food Storage & Preservation', 'food-storage-preservation', 'Pickling, freezing, shelf life', '🫙', 1910),
    -- Sports specifics (1950s)
    ('Chess', 'chess', 'Openings, tactics, ratings, tournaments', '♟️', 1951),
    ('Badminton & Tennis', 'badminton-tennis', 'Racquet sports technique and gear', '🎾', 1952),
    ('Kabaddi & Kho-Kho', 'kabaddi-kho-kho', 'Indian traditional sports', '🤼', 1953),
    ('Hockey', 'hockey', 'Field hockey in India and worldwide', '🏑', 1954),
    ('Running & Athletics', 'running-athletics', 'Marathons, sprinting, training plans', '🏃', 1955),
    ('Swimming', 'swimming', 'Learning, technique, competitions', '🏊', 1956),
    ('Motorsports', 'motorsports', 'F1, MotoGP, racing in India', '🏎️', 1957),
    ('Wrestling & Boxing', 'wrestling-boxing', 'Combat sports, training, events', '🥊', 1958),
    -- Entertainment specifics (2000s)
    ('Bollywood', 'bollywood', 'Hindi cinema, stars, box office', '🎥', 2001),
    ('South Indian Cinema', 'south-indian-cinema', 'Tamil, Telugu, Kannada, Malayalam films', '🌟', 2002),
    ('Hollywood & World Cinema', 'hollywood-world-cinema', 'English and international films', '🎞', 2003),
    ('K-Drama & Korean Wave', 'kdrama-korean-wave', 'K-dramas, K-pop, Korean culture', '🇰🇷', 2004),
    ('Stand-up Comedy', 'standup-comedy', 'Comedians, shows, open mics', '🎙', 2005),
    ('Reality Shows', 'reality-shows', 'Bigg Boss, talent shows, discussions', '📡', 2006),
    ('Theatre & Drama', 'theatre-drama', 'Stage plays, acting, theatre groups', '🎭', 2007),
    ('Podcast Production', 'podcast-production', 'Starting and growing a podcast', '🎚️', 2008),
    ('Voiceover & Dubbing', 'voiceover-dubbing', 'Voice careers, dubbing work', '🎤', 2009),
    ('Online & Real-money Gaming', 'online-real-money-gaming', 'Rummy, poker apps, legality, addiction', '🎰', 2010),
    -- Career fields (2100s)
    ('BPO & Customer Support Jobs', 'bpo-customer-support-jobs', 'Call centers, support careers', '🎧', 2101),
    ('HR & Recruitment', 'hr-recruitment', 'HR careers, hiring, policies', '🗂️', 2102),
    ('Finance & Accounting Jobs', 'finance-accounting-jobs', 'Accountant, analyst, audit careers', '🧾', 2103),
    ('Design Careers', 'design-careers', 'Graphic, product, fashion design jobs', '🖍️', 2104),
    ('Medical & Healthcare Careers', 'medical-healthcare-careers', 'Doctor, nurse, allied health careers', '🩺', 2105),
    ('Legal Careers', 'legal-careers', 'Advocacy, corporate law, judiciary', '⚖️', 2106),
    ('Media & Journalism Careers', 'media-journalism-careers', 'Reporting, editing, content careers', '📰', 2107),
    ('Sales & Field Jobs', 'sales-field-jobs', 'FMCG, pharma, field sales careers', '💼', 2108),
    ('Hospitality Careers', 'hospitality-careers', 'Hotels, restaurants, tourism jobs', '🛎️', 2109),
    ('Logistics & Supply Chain Careers', 'logistics-supply-chain-careers', 'Warehouse, SCM, procurement roles', '📦', 2110),
    -- Home services (2200s)
    ('Packers & Movers', 'packers-movers', 'Shifting homes, choosing movers, claims', '🚚', 2201),
    ('Home Cleaning Services', 'home-cleaning-services', 'Deep cleaning, maids, service apps', '🧽', 2202),
    ('AC Repair & Service', 'ac-repair-service', 'AC installation, gas refill, AMC', '❄️', 2203),
    ('Pest Control', 'pest-control', 'Termites, cockroaches, safe treatments', '🐜', 2204),
    ('Plumbing Help', 'plumbing-help', 'Leaks, fittings, bathroom issues', '🚿', 2205),
    ('Electrical Repairs', 'electrical-repairs', 'Wiring, MCBs, appliance points', '🔌', 2206),
    ('Carpentry & Furniture Work', 'carpentry-furniture-work', 'Custom furniture, repairs, polish', '🪑', 2207),
    ('Painting & Waterproofing', 'painting-waterproofing', 'House painting, seepage, costs', '🖌', 2208),
    ('CCTV & Home Security', 'cctv-home-security', 'Cameras, locks, smart security', '📹', 2209),
    ('Solar Panels & Green Energy', 'solar-panels-green-energy', 'Rooftop solar, subsidies, inverters', '☀️', 2210),
    -- Community & society (2300s)
    ('Weather & Monsoon', 'weather-monsoon', 'Forecasts, monsoon, extreme weather', '🌧️', 2301),
    ('Charity & NGOs', 'charity-ngos', 'Donating, starting NGOs, 80G', '🤲', 2302),
    ('Volunteering', 'volunteering', 'Where and how to volunteer', '🙌', 2303),
    ('Disability & Accessibility', 'disability-accessibility', 'UDID, rights, assistive tech, inclusion', '♿', 2304),
    ('LGBTQ+ Community', 'lgbtq-community', 'Support, rights, coming out, community', '🏳️‍🌈', 2305),
    ('Men''s Grooming', 'mens-grooming', 'Beard care, skincare, style for men', '🪒', 2306),
    ('Minimalism & Frugal Living', 'minimalism-frugal-living', 'Living with less, saving smart', '🧺', 2307),
    ('Genealogy & Family History', 'genealogy-family-history', 'Tracing roots, records, family trees', '🌳', 2308),
    ('Time Management', 'time-management', 'Schedules, prioritization, focus', '⏳', 2309),
    ('Dreams & Sleep Science', 'dreams-sleep-science', 'Dream meanings, sleep cycles', '🌙', 2310),
    -- Extra ecommerce & online work (2400s)
    ('Global Marketplaces (eBay/Etsy)', 'global-marketplaces-ebay-etsy', 'Selling on international platforms', '🌐', 2401),
    ('Payment Disputes & Chargebacks', 'payment-disputes-chargebacks', 'Failed payments, refunds stuck, disputes', '⚠️', 2402),
    ('Ecommerce Careers', 'ecommerce-careers', 'Jobs in ecommerce companies and ops', '🧑‍💼', 2403),
    ('Warehousing & Fulfillment', 'warehousing-fulfillment', 'FBA warehouses, 3PL, storage', '🏬', 2404),
    ('Hyperlocal Delivery Business', 'hyperlocal-delivery-business', 'Local delivery startups and services', '🛴', 2405),
    ('Online Surveys & Microtasks', 'online-surveys-microtasks', 'Legit microtask and survey platforms', '📝', 2406),
    ('Influencer Marketing', 'influencer-marketing', 'Brand deals, rates, collaborations', '🤩', 2407),
    ('WhatsApp Business & Automation', 'whatsapp-business-automation', 'WA Business API, catalogs, chatbots', '💬', 2408),
    ('Customer Loyalty & Retention', 'customer-loyalty-retention', 'Repeat buyers, loyalty programs, CRM', '🔁', 2409),
    ('Ecommerce Fraud & Safety', 'ecommerce-fraud-safety', 'Fake orders, COD abuse, buyer scams', '🛡️', 2410),
    ('Resume Templates & Tools', 'resume-templates-tools', 'ATS-friendly formats, builders, portfolios', '📑', 2111),
    ('Public Speaking & Debating', 'public-speaking-debating', 'Speeches, MUNs, stage confidence', '🎙️', 2311),
    ('Board Games & Card Games', 'board-games-card-games', 'Ludo to Catan — rules and strategy', '🎴', 2011),
    ('Collectibles & Antiques', 'collectibles-antiques', 'Coins, stamps, vintage items, valuation', '🪙', 2312),
    ('Bicycles & Cycling', 'bicycles-cycling', 'Buying, maintenance, cycling routes', '🚴', 1959),
    ('Camping & Outdoor Gear', 'camping-outdoor-gear', 'Tents, gear reviews, campsite tips', '🏕️', 747),
    ('Freight & Import Duties', 'freight-import-duties', 'Customs duty, import taxes, clearance', '🛃', 2411),
    ('Local Business Marketing', 'local-business-marketing', 'Google Maps listing, local ads, footfall', '📍', 2412),
('Uttar Pradesh', 'uttar-pradesh', 'Jobs, schemes and life across UP', '🗺️', 2501),
    ('Maharashtra', 'maharashtra', 'Local questions across Maharashtra', '🗺️', 2502),
    ('Bihar', 'bihar', 'Local questions, exams and schemes in Bihar', '🗺️', 2503),
    ('West Bengal', 'west-bengal', 'Local life across West Bengal', '🗺️', 2504),
    ('Madhya Pradesh', 'madhya-pradesh', 'Local questions across MP', '🗺️', 2505),
    ('Tamil Nadu', 'tamil-nadu', 'Local life across Tamil Nadu', '🗺️', 2506),
    ('Rajasthan', 'rajasthan', 'Local questions across Rajasthan', '🗺️', 2507),
    ('Karnataka', 'karnataka', 'Local life across Karnataka', '🗺️', 2508),
    ('Gujarat', 'gujarat', 'Local questions across Gujarat', '🗺️', 2509),
    ('Andhra Pradesh', 'andhra-pradesh', 'Local life across Andhra Pradesh', '🗺️', 2510),
    ('Odisha', 'odisha', 'Local questions across Odisha', '🗺️', 2511),
    ('Telangana', 'telangana', 'Local life across Telangana', '🗺️', 2512),
    ('Kerala', 'kerala', 'Local questions across Kerala', '🗺️', 2513),
    ('Jharkhand', 'jharkhand', 'Local life across Jharkhand', '🗺️', 2514),
    ('Assam', 'assam', 'Local questions across Assam', '🗺️', 2515),
    ('Punjab', 'punjab', 'Local life across Punjab', '🗺️', 2516),
    ('Chhattisgarh', 'chhattisgarh', 'Local questions across Chhattisgarh', '🗺️', 2517),
    ('Haryana', 'haryana', 'Local life across Haryana', '🗺️', 2518),
    ('Uttarakhand', 'uttarakhand', 'Hills, tourism and life in Uttarakhand', '🗺️', 2519),
    ('Himachal Pradesh', 'himachal-pradesh', 'Local life across Himachal', '🗺️', 2520),
    ('Tripura & Meghalaya', 'tripura-meghalaya', 'Northeast states — local questions', '🗺️', 2521),
    ('Manipur & Nagaland', 'manipur-nagaland', 'Northeast states — local life', '🗺️', 2522),
    ('Arunachal & Mizoram', 'arunachal-mizoram', 'Northeast frontier states', '🗺️', 2523),
    ('Sikkim', 'sikkim', 'Local life and travel in Sikkim', '🗺️', 2524),
    ('Jammu & Kashmir', 'jammu-kashmir', 'Local life and travel in J&K', '🗺️', 2525),
    ('Ladakh', 'ladakh', 'Life and travel in Ladakh', '🗺️', 2526),
    ('Puducherry & Andaman', 'puducherry-andaman', 'Union territories — local questions', '🗺️', 2527),
    ('North East India (General)', 'north-east-india-general', 'Cross-cutting Northeast questions', '🗺️', 2528),
    ('USA — Living & Visas', 'usa-living-visas', 'H1B, green card, life in America', '🌍', 2601),
    ('UK — Living & Visas', 'uk-living-visas', 'Student and work visas, life in UK', '🌍', 2602),
    ('Canada — Living & PR', 'canada-living-pr', 'Express Entry, study, settling in Canada', '🌍', 2603),
    ('Australia — Living & Visas', 'australia-living-visas', 'Skilled migration, study, life', '🌍', 2604),
    ('UAE & Dubai', 'uae-dubai', 'Jobs, visas and life in the Gulf', '🌍', 2605),
    ('Saudi Arabia & Gulf', 'saudi-arabia-gulf', 'Work and life in GCC countries', '🌍', 2606),
    ('Singapore', 'singapore', 'Work passes, study, living costs', '🌍', 2607),
    ('Germany — Study & Work', 'germany-study-work', 'Ausbildung, job seeker visa, life', '🌍', 2608),
    ('Europe — Schengen & Life', 'europe-schengen-life', 'EU travel, study and work', '🌍', 2609),
    ('Japan — Study & Work', 'japan-study-work', 'Language, visas, working in Japan', '🌍', 2610),
    ('South Korea', 'south-korea', 'Study, work and K-culture on the ground', '🌍', 2611),
    ('China & Hong Kong', 'china-hong-kong', 'Business, study and travel', '🌍', 2612),
    ('Russia & CIS', 'russia-cis', 'MBBS abroad, travel, trade', '🌍', 2613),
    ('Nepal & Bhutan', 'nepal-bhutan', 'Travel and cross-border questions', '🌍', 2614),
    ('Sri Lanka & Maldives', 'sri-lanka-maldives', 'Travel and regional questions', '🌍', 2615),
    ('Bangladesh & Pakistan', 'bangladesh-pakistan', 'Regional and cross-border topics', '🌍', 2616),
    ('Africa — Work & Trade', 'africa-work-trade', 'Jobs, business and travel in Africa', '🌍', 2617),
    ('South America', 'south-america', 'Travel and life across South America', '🌍', 2618),
    ('New Zealand', 'new-zealand', 'Study, work and PR pathways', '🌍', 2619),
    ('Ireland', 'ireland', 'Study and tech jobs in Ireland', '🌍', 2620),
    ('MBBS Abroad', 'mbbs-abroad', 'Medical education outside India', '🌍', 2621),
    ('Immigration & PR (General)', 'immigration-pr-general', 'Comparing countries, consultants, IELTS bands', '🌍', 2622),
    ('International Jobs', 'international-jobs', 'Finding overseas work safely', '🌍', 2623),
    ('Overseas Education Loans', 'overseas-education-loans', 'Funding foreign degrees', '🌍', 2624),
    ('Travel Insurance & Forex Cards', 'travel-insurance-forex-cards', 'Money matters when abroad', '🌍', 2625),
    ('Git & GitHub', 'git-github', 'Version control, PRs, collaboration', '🧰', 2701),
    ('Docker & Containers', 'docker-containers', 'Images, compose, deployment', '🧰', 2702),
    ('Kubernetes', 'kubernetes', 'Clusters, helm, orchestration', '🧰', 2703),
    ('Firebase & Supabase', 'firebase-supabase', 'BaaS, auth, realtime databases', '🧰', 2704),
    ('MongoDB', 'mongodb', 'Documents, aggregation, Atlas', '🧰', 2705),
    ('PostgreSQL', 'postgresql', 'Queries, indexing, administration', '🧰', 2706),
    ('MySQL & MariaDB', 'mysql-mariadb', 'Schema design, tuning, backups', '🧰', 2707),
    ('Redis & Caching', 'redis-caching', 'Caching strategies, queues', '🧰', 2708),
    ('GraphQL & REST Design', 'graphql-rest-design', 'API design and schemas', '🧰', 2709),
    ('Next.js & Modern Web', 'next-js-modern-web', 'SSR, app router, deployment', '🧰', 2710),
    ('Tailwind CSS', 'tailwind-css', 'Utility CSS, components, themes', '🧰', 2711),
    ('Bootstrap & UI Kits', 'bootstrap-ui-kits', 'Frontend component libraries', '🧰', 2712),
    ('Unity Engine', 'unity-engine', 'Unity game development', '🧰', 2713),
    ('Unreal Engine', 'unreal-engine', 'UE5, blueprints, rendering', '🧰', 2714),
    ('Figma', 'figma', 'Design files, prototypes, plugins', '🧰', 2715),
    ('Notion & Docs Tools', 'notion-docs-tools', 'Workspaces, templates, wikis', '🧰', 2716),
    ('Jira & Agile Tools', 'jira-agile-tools', 'Scrum, kanban, project tracking', '🧰', 2717),
    ('Salesforce', 'salesforce', 'CRM administration and development', '🧰', 2718),
    ('SAP & ERP', 'sap-erp', 'SAP modules, ERP careers', '🧰', 2719),
    ('Power BI', 'power-bi', 'Dashboards, DAX, reports', '🧰', 2720),
    ('Tableau', 'tableau', 'Visual analytics and dashboards', '🧰', 2721),
    ('MATLAB & Simulink', 'matlab-simulink', 'Engineering computation', '🧰', 2722),
    ('AutoCAD', 'autocad', 'Drafting and CAD workflows', '🧰', 2723),
    ('SolidWorks & 3D CAD', 'solidworks-3d-cad', 'Mechanical design tools', '🧰', 2724),
    ('Raspberry Pi Projects', 'raspberry-pi-projects', 'Single-board computer builds', '🧰', 2725),
    ('Home Assistant & Automation', 'home-assistant-automation', 'Self-hosted smart home', '🧰', 2726),
    ('ChatGPT & AI Assistants', 'chatgpt-ai-assistants', 'Using AI tools effectively', '🧰', 2727),
    ('AI Image & Video Tools', 'ai-image-video-tools', 'Midjourney, SD, AI media', '🧰', 2728),
    ('AI Coding Assistants', 'ai-coding-assistants', 'Copilot, Claude Code, Cursor workflows', '🧰', 2729),
    ('Zapier & Make', 'zapier-make', 'Cross-app automations', '🧰', 2730),
    ('Fishing & Angling', 'fishing-angling', 'Spots, gear, techniques', '🎨', 2801),
    ('Bird Watching', 'bird-watching', 'Birding spots, identification, gear', '🎨', 2802),
    ('Amateur Astronomy', 'amateur-astronomy', 'Telescopes, skywatching, astrophotography', '🎨', 2803),
    ('Painting & Sketching', 'painting-sketching', 'Mediums, techniques, learning', '🎨', 2804),
    ('Calligraphy & Lettering', 'calligraphy-lettering', 'Scripts, tools, practice', '🎨', 2805),
    ('Origami & Paper Craft', 'origami-paper-craft', 'Folds, models, paper art', '🎨', 2806),
    ('Pottery & Ceramics', 'pottery-ceramics', 'Wheel work, clay, glazing', '🎨', 2807),
    ('Woodworking', 'woodworking', 'Tools, joinery, projects', '🎨', 2808),
    ('Knitting & Crochet', 'knitting-crochet', 'Patterns, yarn, techniques', '🎨', 2809),
    ('Embroidery & Stitching', 'embroidery-stitching', 'Hand and machine embroidery', '🎨', 2810),
    ('Jewellery Making', 'jewellery-making', 'Beading, metalwork, selling crafts', '🎨', 2811),
    ('Candle & Soap Making', 'candle-soap-making', 'Home crafting and small business', '🎨', 2812),
    ('Aquariums & Fishkeeping', 'aquariums-fishkeeping', 'Tanks, species, maintenance', '🎨', 2813),
    ('Bonsai & Plant Art', 'bonsai-plant-art', 'Bonsai care and styling', '🎨', 2814),
    ('Magic & Illusions', 'magic-illusions', 'Tricks, sleight of hand, performing', '🎨', 2815),
    ('Speedcubing & Puzzles', 'speedcubing-puzzles', 'Rubik''s cubes, mechanical puzzles', '🎨', 2816),
    ('RC Models & Drones Hobby', 'rc-models-drones-hobby', 'RC cars, planes, hobby drones', '🎨', 2817),
    ('Kite Flying', 'kite-flying', 'Kites, manjha safety, festivals', '🎨', 2818),
    ('Wildlife Photography', 'wildlife-photography', 'Safaris, gear, technique', '🎨', 2819),
    ('Wedding Photography', 'wedding-photography', 'Business and craft of wedding shoots', '🎨', 2820),
    ('Sculpting & Clay Art', 'sculpting-clay-art', '3D art and materials', '🎨', 2821),
    ('Model Trains & Dioramas', 'model-trains-dioramas', 'Scale modeling', '🎨', 2822),
    ('Stamp & Coin Collecting', 'stamp-coin-collecting', 'Philately and numismatics', '🎨', 2823),
    ('Quilling & Paper Flowers', 'quilling-paper-flowers', 'Decorative paper craft', '🎨', 2824),
    ('DIY Gifts & Decor', 'diy-gifts-decor', 'Handmade gifting ideas', '🎨', 2825),
    ('Dog Training', 'dog-training', 'Obedience, behaviour, commands', '🐾', 2901),
    ('Dog Breeds & Adoption', 'dog-breeds-adoption', 'Choosing and adopting dogs', '🐾', 2902),
    ('Cat Care', 'cat-care', 'Feeding, litter, behaviour', '🐾', 2903),
    ('Pet Birds', 'pet-birds', 'Parrots, budgies, care and cages', '🐾', 2904),
    ('Pet Food & Nutrition', 'pet-food-nutrition', 'Diets, brands, homemade food', '🐾', 2905),
    ('Pet Health & Vets', 'pet-health-vets', 'Illness, vaccines, finding vets', '🐾', 2906),
    ('Pet Grooming', 'pet-grooming', 'Coat care, bathing, nails', '🐾', 2907),
    ('Exotic Pets', 'exotic-pets', 'Turtles, hamsters, legal exotics', '🐾', 2908),
    ('Stray & Animal Welfare', 'stray-animal-welfare', 'Rescue, feeding strays, ABC programs', '🐾', 2909),
    ('Pet Travel & Relocation', 'pet-travel-relocation', 'Flying and moving with pets', '🐾', 2910),
    ('Research & Publications', 'research-publications', 'Papers, journals, citations', '🎓', 3001),
    ('Thesis & Dissertation', 'thesis-dissertation', 'Writing and defending research', '🎓', 3002),
    ('IELTS Preparation', 'ielts-preparation', 'Band strategies, modules, practice', '🎓', 3003),
    ('TOEFL & PTE', 'toefl-pte', 'English tests for abroad', '🎓', 3004),
    ('GRE Preparation', 'gre-preparation', 'Quant, verbal, test strategy', '🎓', 3005),
    ('GMAT & Executive MBA', 'gmat-executive-mba', 'B-school tests and applications', '🎓', 3006),
    ('SAT & International UG', 'sat-international-ug', 'Undergrad admissions abroad', '🎓', 3007),
    ('Statement of Purpose & Essays', 'statement-of-purpose-essays', 'SOPs, LORs, application writing', '🎓', 3008),
    ('Coding Bootcamps', 'coding-bootcamps', 'Are bootcamps worth it, reviews', '🎓', 3009),
    ('Academic Writing', 'academic-writing', 'Structure, style, citations', '🎓', 3010),
    ('Plagiarism & Research Ethics', 'plagiarism-research-ethics', 'Originality, tools, integrity', '🎓', 3011),
    ('PhD Life & Academia', 'phd-life-academia', 'Advisors, funding, postdocs', '🎓', 3012),
    ('Homeschooling & Alt Education', 'homeschooling-alt-education', 'NIOS, homeschooling in India', '🎓', 3013),
    ('School Admissions', 'school-admissions', 'Nursery to Class 11 admissions', '🎓', 3014),
    ('Education Technology', 'education-technology', 'Apps and tools for learning', '🎓', 3015),
    ('Buying a New Car', 'buying-a-new-car', 'Models, negotiations, on-road price', '🚙', 3101),
    ('Used Car Buying', 'used-car-buying', 'Inspection, valuation, paperwork', '🚙', 3102),
    ('Car Maintenance', 'car-maintenance', 'Servicing, DIY care, costs', '🚙', 3103),
    ('Bike Maintenance', 'bike-maintenance', 'Two-wheeler servicing and care', '🚙', 3104),
    ('Electric Cars', 'electric-cars', 'EV models, range, ownership', '🚙', 3105),
    ('Electric Scooters', 'electric-scooters', 'E-scooter buying and issues', '🚙', 3106),
    ('Car Accessories & Care', 'car-accessories-care', 'Dashcams, seat covers, detailing', '🚙', 3107),
    ('Driving Tips & Safety', 'driving-tips-safety', 'Defensive driving, highway rules', '🚙', 3108),
    ('Commercial Vehicles', 'commercial-vehicles', 'Trucks, tempos, fleet questions', '🚙', 3109),
    ('Tractors & Farm Vehicles', 'tractors-farm-vehicles', 'Agri machinery buying and care', '🚙', 3110),
    ('Luxury & Performance Cars', 'luxury-performance-cars', 'Premium car ownership', '🚙', 3111),
    ('Vintage & Classic Vehicles', 'vintage-classic-vehicles', 'Restoration and collecting', '🚙', 3112),
    ('Car Audio & Infotainment', 'car-audio-infotainment', 'Android Auto, speakers, screens', '🚙', 3113),
    ('Tyres & Batteries', 'tyres-batteries', 'Choosing and maintaining consumables', '🚙', 3114),
    ('Vehicle Insurance & Claims', 'vehicle-insurance-claims', 'Motor insurance, accident claims', '🚙', 3115),
    ('Remittance & Money Transfer', 'remittance-money-transfer', 'Sending money in and out of India', '💹', 3201),
    ('Demat & Brokers', 'demat-brokers', 'Choosing brokers, account issues', '💹', 3202),
    ('Tax for Freelancers', 'tax-for-freelancers', '44ADA, GST, advance tax for independents', '💹', 3203),
    ('Wills & Inheritance', 'wills-inheritance', 'Succession, nominee, property transfer', '💹', 3204),
    ('HUF & Family Finance', 'huf-family-finance', 'HUF accounts, joint family money', '💹', 3205),
    ('Chit Funds & Societies', 'chit-funds-societies', 'Co-op societies, chit safety', '💹', 3206),
    ('Budgeting Apps & Tools', 'budgeting-apps-tools', 'Trackers, spreadsheets, methods', '💹', 3207),
    ('Teaching Kids About Money', 'teaching-kids-about-money', 'Financial literacy for children', '💹', 3208),
    ('Couple & Family Budgeting', 'couple-family-budgeting', 'Joint finances, money talks', '💹', 3209),
    ('Emergency Funds', 'emergency-funds', 'How much, where to park', '💹', 3210),
    ('REITs & Alternative Assets', 'reits-alternative-assets', 'REITs, InvITs, P2P lending', '💹', 3211),
    ('Microfinance & SHGs', 'microfinance-shgs', 'Self-help groups, small credit', '💹', 3212),
    ('Savings Accounts & FDs Comparison', 'savings-accounts-fds-comparison', 'Best rates and switching', '💹', 3213),
    ('Credit Score Repair', 'credit-score-repair', 'Improving CIBIL, disputes', '💹', 3214),
    ('Wealth Management & HNI', 'wealth-management-hni', 'PMS, family offices, advisory', '💹', 3215),
    ('Hinduism', 'hinduism', 'Scriptures, practices, philosophy', '🕉️', 3301),
    ('Islam', 'islam', 'Practices, questions, community', '🕉️', 3302),
    ('Christianity', 'christianity', 'Faith, church, community questions', '🕉️', 3303),
    ('Sikhism', 'sikhism', 'Gurbani, practices, community', '🕉️', 3304),
    ('Buddhism & Jainism', 'buddhism-jainism', 'Philosophy and practice', '🕉️', 3305),
    ('Diwali & Festive Prep', 'diwali-festive-prep', 'Cleaning, gifts, celebrations', '🕉️', 3306),
    ('Ramadan & Eid', 'ramadan-eid', 'Fasting, prayers, celebrations', '🕉️', 3307),
    ('Christmas & New Year', 'christmas-new-year', 'Celebrations and planning', '🕉️', 3308),
    ('Navratri & Durga Puja', 'navratri-durga-puja', 'Regional festival questions', '🕉️', 3309),
    ('Vrat & Fasting', 'vrat-fasting', 'Fasting rules and recipes', '🕉️', 3310),
    ('Mantras & Chanting', 'mantras-chanting', 'Meaning, practice, pronunciation', '🕉️', 3311),
    ('Interfaith Questions', 'interfaith-questions', 'Respectful cross-faith curiosity', '🕉️', 3312),
    ('Learn English Grammar', 'learn-english-grammar', 'Rules, tenses, common errors', '🈺', 3401),
    ('Learn Hindi', 'learn-hindi', 'Speaking and writing Hindi', '🈺', 3402),
    ('Learn Tamil', 'learn-tamil', 'Tamil for beginners and beyond', '🈺', 3403),
    ('Learn Telugu', 'learn-telugu', 'Telugu language questions', '🈺', 3404),
    ('Learn Kannada', 'learn-kannada', 'Kannada for newcomers to Karnataka', '🈺', 3405),
    ('Learn Malayalam', 'learn-malayalam', 'Malayalam language help', '🈺', 3406),
    ('Learn Bengali', 'learn-bengali', 'Bengali language questions', '🈺', 3407),
    ('Learn Marathi', 'learn-marathi', 'Marathi for Maharashtra life', '🈺', 3408),
    ('Learn Gujarati', 'learn-gujarati', 'Gujarati language help', '🈺', 3409),
    ('Learn Punjabi', 'learn-punjabi', 'Punjabi language questions', '🈺', 3410),
    ('Learn Urdu', 'learn-urdu', 'Urdu script and speech', '🈺', 3411),
    ('Learn French & German', 'learn-french-german', 'European languages from India', '🈺', 3412),
    ('Learn Spanish', 'learn-spanish', 'Spanish learning path', '🈺', 3413),
    ('Learn Japanese & Korean', 'learn-japanese-korean', 'JLPT, TOPIK, scripts', '🈺', 3414),
    ('Organic Farming', 'organic-farming', 'Certification, inputs, markets', '🌾', 3501),
    ('Hydroponics & Soilless', 'hydroponics-soilless', 'Setups, nutrients, viability', '🌾', 3502),
    ('Mushroom Farming', 'mushroom-farming', 'Oyster, button — growing and selling', '🌾', 3503),
    ('Beekeeping', 'beekeeping', 'Hives, honey business', '🌾', 3504),
    ('Goat & Sheep Farming', 'goat-sheep-farming', 'Breeds, sheds, economics', '🌾', 3505),
    ('Poultry Farming', 'poultry-farming', 'Layers, broilers, disease control', '🌾', 3506),
    ('Fish & Prawn Farming', 'fish-prawn-farming', 'Aquaculture ponds and RAS', '🌾', 3507),
    ('Drip & Irrigation', 'drip-irrigation', 'Water systems and subsidies', '🌾', 3508),
    ('Seeds & Fertilizers', 'seeds-fertilizers', 'Varieties, dosage, sourcing', '🌾', 3509),
    ('Crop Diseases & Pests', 'crop-diseases-pests', 'Identification and treatment', '🌾', 3510),
    ('Farm Machinery', 'farm-machinery', 'Tractors, implements, rentals', '🌾', 3511),
    ('Mandi Prices & Agri Marketing', 'mandi-prices-agri-marketing', 'Selling produce, eNAM, MSP', '🌾', 3512),
    ('Greenhouse & Polyhouse', 'greenhouse-polyhouse', 'Protected cultivation', '🌾', 3513),
    ('Dairy Farming', 'dairy-farming', 'Cattle, milk business, chilling', '🌾', 3514),
    ('Long Distance Relationships', 'long-distance-relationships', 'Making LDRs work', '💞', 3601),
    ('Breakups & Moving On', 'breakups-moving-on', 'Healing and starting over', '💞', 3602),
    ('Friendship', 'friendship', 'Making and keeping friends as adults', '💞', 3603),
    ('Single Life', 'single-life', 'Living well while single', '💞', 3604),
    ('Divorce & Separation', 'divorce-separation', 'Legal process and emotional support', '💞', 3605),
    ('Second Marriage', 'second-marriage', 'Remarriage questions and blended families', '💞', 3606),
    ('Pregnancy & Childbirth', 'pregnancy-childbirth', 'Trimesters, delivery, hospitals', '💞', 3607),
    ('New Parents (0-2 yrs)', 'new-parents-0-2-yrs', 'Newborn care, sleep, feeding', '💞', 3608),
    ('Raising Teenagers', 'raising-teenagers', 'Teen behaviour, phones, studies', '💞', 3609),
    ('Empty Nest & Midlife', 'empty-nest-midlife', 'Life after kids grow up', '💞', 3610),
    ('Retirement Life', 'retirement-life', 'Purpose, money and health after 60', '💞', 3611),
    ('Caring for Aging Parents', 'caring-for-aging-parents', 'Eldercare, health, living arrangements', '💞', 3612),
    ('YouTube Growth', 'youtube-growth', 'Algorithm, niches, analytics', '📹', 3701),
    ('Instagram Reels & Growth', 'instagram-reels-growth', 'Reels strategy, engagement', '📹', 3702),
    ('Short Video Apps', 'short-video-apps', 'Moj, Josh, YT Shorts strategy', '📹', 3703),
    ('Live Streaming', 'live-streaming', 'YouTube/Twitch live setups', '📹', 3704),
    ('SEO Content Writing', 'seo-content-writing', 'Ranking articles, keyword research', '📹', 3705),
    ('Newsletters & Substack', 'newsletters-substack', 'Email audiences and monetization', '📹', 3706),
    ('Cameras & Creator Gear', 'cameras-creator-gear', 'Mics, lights, budget setups', '📹', 3707),
    ('Thumbnails & Packaging', 'thumbnails-packaging', 'CTR, titles, presentation', '📹', 3708),
    ('Copyright & Fair Use', 'copyright-fair-use', 'Music, clips, strikes, licensing', '📹', 3709),
    ('AdSense & Monetization', 'adsense-monetization', 'Enabling and growing ad income', '📹', 3710),
    ('Community Building', 'community-building', 'Discord, Telegram, fan engagement', '📹', 3711),
    ('Creator Burnout & Consistency', 'creator-burnout-consistency', 'Sustainable content careers', '📹', 3712),
    ('RTI Applications', 'rti-applications', 'Filing RTIs, appeals, formats', '📋', 3801),
    ('Police & FIR Help', 'police-fir-help', 'Filing FIRs, complaints, rights', '📋', 3802),
    ('Court Procedures', 'court-procedures', 'Cases, dates, lawyers, e-courts', '📋', 3803),
    ('Notary & Affidavits', 'notary-affidavits', 'Formats, stamp papers, attestation', '📋', 3804),
    ('Property Registration & Stamp Duty', 'property-registration-stamp-duty', 'Registry process and charges', '📋', 3805),
    ('Gas Connection & LPG', 'gas-connection-lpg', 'New connections, subsidy, refills', '📋', 3806),
    ('Ration Card & PDS', 'ration-card-pds', 'Applying, corrections, entitlements', '📋', 3807),
    ('Caste & Income Certificates', 'caste-income-certificates', 'Applying and using certificates', '📋', 3808),
    ('Birth & Death Certificates', 'birth-death-certificates', 'Registration and corrections', '📋', 3809),
    ('Marriage Registration', 'marriage-registration', 'Court marriage, certificates', '📋', 3810),
    ('Pension & Family Pension', 'pension-family-pension', 'Government and private pensions', '📋', 3811),
    ('Army & Veteran Affairs', 'army-veteran-affairs', 'ECHS, canteen, veteran benefits', '📋', 3812),
    ('Consumer Court & Refunds', 'consumer-court-refunds', 'Filing consumer complaints', '📋', 3813),
    ('Municipal & Property Tax', 'municipal-property-tax', 'House tax, khata, mutations', '📋', 3814),
    ('How Things Work', 'how-things-work', 'Everyday science explained', '🧠', 3901),
    ('World History', 'world-history', 'Global events and eras', '🧠', 3902),
    ('Indian Freedom Struggle', 'indian-freedom-struggle', 'Independence movement history', '🧠', 3903),
    ('Mythology & Epics', 'mythology-epics', 'Ramayana, Mahabharata, world myths', '🧠', 3904),
    ('Space Missions', 'space-missions', 'ISRO, NASA, SpaceX missions', '🧠', 3905),
    ('Human Body & Anatomy', 'human-body-anatomy', 'How our bodies work', '🧠', 3906),
    ('Animals & Wildlife', 'animals-wildlife', 'Species, behaviour, conservation', '🧠', 3907),
    ('Oceans & Marine Life', 'oceans-marine-life', 'Marine ecosystems', '🧠', 3908),
    ('Inventions & Discoveries', 'inventions-discoveries', 'Who invented what and how', '🧠', 3909),
    ('Future Tech & Predictions', 'future-tech-predictions', 'What''s coming next', '🧠', 3910),
    ('Riddles & Brain Teasers', 'riddles-brain-teasers', 'Logic puzzles to solve together', '🧠', 3911),
    ('General Knowledge & Trivia', 'general-knowledge-trivia', 'GK for exams and fun', '🧠', 3912),
    ('Tailoring & Boutique', 'tailoring-boutique', 'Stitching, boutique business, alterations', '🧵', 4001),
    ('Mobile Repair Business', 'mobile-repair-business', 'Phone repair skills and shop setup', '🔧', 4002),
    ('Tuition & Coaching Centre', 'tuition-coaching-centre', 'Starting and running tuition classes', '📚', 4003),
    ('Tea Stall & Small Eatery', 'tea-stall-small-eatery', 'Chai stalls, dhabas, small food outlets', '🫖', 4004),
    ('Gym & Fitness Business', 'gym-fitness-business', 'Opening gyms, trainers, memberships', '🏋️', 4005),
    ('Photography Business', 'photography-business', 'Studios, pricing, client handling', '📷', 4006),
    ('Printing & Xerox Shop', 'printing-xerox-shop', 'Print shops, flex, DTP services', '🖨️', 4007),
    ('Mobile & Electronics Shop', 'mobile-electronics-shop', 'Retail electronics business', '🏪', 4008),
    ('Grocery & Kirana Store', 'grocery-kirana-store', 'Kirana business, margins, suppliers', '🛒', 4009),
    ('Medical Store Business', 'medical-store-business', 'Pharmacy retail, licenses, stock', '💊', 4010),
    ('Stationery & Book Shop', 'stationery-book-shop', 'School supplies retail business', '✏️', 4011),
    ('Water Purifier & RO Business', 'water-purifier-ro-business', 'RO sales, service and installation', '💧', 4012),
    ('Cyber Cafe & CSC Centre', 'cyber-cafe-csc-centre', 'Common service centres, online services shop', '🖥️', 4013),
    ('Beauty Parlour at Home', 'beauty-parlour-home', 'Home salon services business', '💅', 4014),
    ('Tiffin Service Business', 'tiffin-service-business', 'Home food delivery business', '🍱', 4015),
    ('Bakery Business', 'bakery-business', 'Cakes and bakery shop setup', '🧁', 4016),
    ('Poultry & Egg Shop', 'poultry-egg-shop', 'Meat and egg retail business', '🥚', 4017),
    ('Hardware & Paint Shop', 'hardware-paint-shop', 'Building materials retail', '🪛', 4018),
    ('Garment Shop', 'garment-shop', 'Clothing retail business', '👕', 4019),
    ('Footwear Business', 'footwear-business', 'Shoe retail and wholesale', '👟', 4020),
    ('Toy & Gift Shop', 'toy-gift-shop', 'Toys and gifting retail', '🧸', 4021),
    ('Vegetable & Fruit Vending', 'vegetable-fruit-vending', 'Fresh produce selling business', '🥕', 4022),
    ('Flower & Pooja Shop', 'flower-pooja-shop', 'Flowers, garlands, pooja samagri', '🌸', 4023),
    ('Two-Wheeler Showroom & Service', 'two-wheeler-showroom-service', 'Bike dealership and service business', '🏍', 4024),
    ('Car Wash & Detailing Business', 'car-wash-detailing-business', 'Vehicle cleaning services', '🚿', 4025),
    ('Laundry & Dry Cleaning', 'laundry-dry-cleaning', 'Laundry business and services', '🧺', 4026),
    ('Courier Franchise', 'courier-franchise', 'Delhivery, DTDC franchise business', '📦', 4027),
    ('ATM & Banking Kiosk', 'atm-banking-kiosk', 'Banking correspondent, kiosk business', '🏧', 4028),
    ('Petrol Pump & Gas Agency', 'petrol-pump-gas-agency', 'Fuel dealership process and economics', '⛽', 4029),
    ('Real Estate Rental Income', 'real-estate-rental-income', 'PGs, rentals, commercial leasing', '🏘', 4030),
    ('Vending Machines & Kiosks', 'vending-machines-kiosks', 'Automated retail business', '🥤', 4031),
    ('Import from China Guide', 'import-from-china-guide', 'Alibaba, sourcing agents, customs', '🛳️', 4032);
